### ISSUE TITLE
Terminology and FAQs Section Links are broken

### ISSUE THREAD

**Issue by YajJackson** [Unity-Technologies/com.unity.multiplayer.docs#1000]
**Describe the bug:**
The following links on https://docs-multiplayer.unity3d.com/netcode/current/about are broken

**Steps to reproduce the behavior:**
1. Navigate to https://docs-multiplayer.unity3d.com/netcode/current/about
2. Click any of the following links:
    - [High Level Terminology](https://docs-multiplayer.unity3d.com/netcode/current/reference/glossary/high-level-terminology.md)
    - [Multiplayer Game Architecture](https://docs-multiplayer.unity3d.com/netcode/current/learn/multiplayer_game_arch_intro.md)
3. See error

**Expected behavior:**
Links are not broken.

**Comment by armstrongl** [comment]
Thanks for reporting this, @YajJackson. We recently overhauled the FAQs and glossary and forgot to remove these links to the old content. We'll push out a fix soon!

**Comment by s-omeilia-unity** [comment]
This fix went in but didn't close the issue
