### ISSUE TITLE
Feedback for ocs/basics/networkvariable.md

### ISSUE THREAD

**Issue by ezoray** [Unity-Technologies/com.unity.multiplayer.docs#1007]
Under Permissions the page states:

"Important
Since Netcode for GameObjects uses a server authoritative model, the server will always have read or write permissions to any NetworkVariable. As an example, if you set both the read and write permissions to Owner the server can still read and write to the NetworkVariable."

This is incorrect, the server doesn't have write permission when write permission is set to owner and a client is the owner of the object.

References:
[https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/issues/2154](https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/issues/2154)
[https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/755](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/755)

**Comment by s-omeilia-unity** [comment]
Note updated and will be live EOD
