### ISSUE TITLE
Feedback for /docs/components/networkmanager.md

### ISSUE THREAD

**Issue by RuchirRaj** [Unity-Technologies/com.unity.multiplayer.docs#101]
**Provide Feedback on Docs**
Please add links to where it's written name of components and other terms like in unity's documentation for easier accessibility 

**Specific page:**
If you clicked Log an issue through the site, the doc file is in the issue title. Or add a link to the page you want to give feedback on.

**About the site:**
What would you like to see on the website?

**Comment by Briancoughlin** [comment]
I think this is about adding API crosslinks to components in main pages will investigate and see how we can do this. It looks like it might be possible. https://dotnet.github.io/docfx/tutorial/links_and_cross_references.html

**Comment by lkrell** [comment]
This may be a larger effort. Will check it out!

**Comment by Briancoughlin** [comment]
Currently not possible will be added as a potential task in JIRA
