### ISSUE TITLE
Feedback for ocs/learn/listenserverhostarchitecture.md

### ISSUE THREAD

**Issue by ssafreno** [Unity-Technologies/com.unity.multiplayer.docs#1011]
There are polish issues, including grammatical mistakes, missing periods, and unclear writing.

Example 1 (missing period):
"Often NAT punching can fail this depends on the type of NATs which is between the clients."
Potential fix: 
"Often NAT punching can fail. This depends on the type of NATs which is between the clients."

Example 2 (grammatical mistake and missing period):
"The advantages of doing this compared to a direct connection is that connecting to a Relay server should always work for any client another advantage is that the Relay server can know when the host client disconnects and inform other clients about that or start a host migration process."
Potential fix:
"One advantage of doing this compared to a direct connection is that connecting to a Relay server should always work for any client. Another advantage is that the Relay server can know when the host client disconnects and inform other clients about that or start a host migration process."

These are just examples. There are other polish issues.

**Comment by ssafreno** [comment]
There is also a spelling mistake:
"They usually charge a cost based on the CCU (conccurrent users)."

conccurrent should be concurrent

**Comment by s-omeilia-unity** [comment]
Reviewing this entire doc for grammar/typos/clarity and will push to live by EOD May 9th.

**Comment by s-omeilia-unity** [comment]
Being published with this PR: https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/1059
