### ISSUE TITLE
Feedback for ocs/api/Unity.Netcode.SceneEventType.md

### ISSUE THREAD

**Issue by mchrpt** [Unity-Technologies/com.unity.multiplayer.docs#1014]
Markdown table does not display properly
![9d5923340b23a13fced83fd07a0fd064](https://user-images.githubusercontent.com/60634882/230487351-87172de9-fadf-42ec-8340-71fa8d6b856e.png)

**Comment by s-omeilia-unity** [comment]
This issue has been resolved
