### ISSUE TITLE
Feedback for /docs/migration/migratingtomlapi.md

### ISSUE THREAD

**Issue by IsaiahKelly** [Unity-Technologies/com.unity.multiplayer.docs#102]
> ...and ClientRPCAttribute has been renamed ClientRPCAttribute 😕

**Specific page:** [Migrating From UNet to MLAPI](https://mp-docs.dl.it.unity3d.com/docs/migration/migratingtomlapi)

**Comment by Briancoughlin** [comment]
covered in pull request 102 can be closed when merged

**Comment by Briancoughlin** [comment]
@IsaiahKelly  we have now fixed this thanks for your contributions
