### ISSUE TITLE
Feedback for ocs/learn/clientside-interpolation.md

### ISSUE THREAD

**Issue by salihcnkhy** [Unity-Technologies/com.unity.multiplayer.docs#1022]
https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/main/Assets/Scripts/Gameplay/GameplayObjects/ClientProjectileVisualization.cs

The link of ClientProjectileVisualization.cs doesn't work. 

You can check the page at: https://docs-multiplayer.unity3d.com/netcode/current/learn/clientside_interpolation#boss-room-example

I couldn't find the file inside the example repository.

**Comment by s-omeilia-unity** [comment]
Looking into where the updated location for this is

**Comment by s-omeilia-unity** [comment]
Links have been updated by @fernando-cortez
