### ISSUE TITLE
Feedback for ransport/install.md

### ISSUE THREAD

**Issue by Graftax** [Unity-Technologies/com.unity.multiplayer.docs#1027]
1. It says it is compatible with 2020.1.2f1 or later. 
2. Use 2020.3.2f1.
3. Notice that there is no "Add package by name" option, only disk, tarball, or URL.

**Comment by s-omeilia-unity** [comment]
Investigating

**Comment by s-omeilia-unity** [comment]
Hi @Graftax,
As of a few weeks ago, the Unity Editor 2020.3 is not supported anymore. The current LTS version is 2021.3.7f1, but the Transport package is presently available from the 2021.1.18f1 and later.
