### ISSUE TITLE
Main content section too small on small screen

### ISSUE THREAD

**Issue by LeLocTai** [Unity-Technologies/com.unity.multiplayer.docs#103]
I usually use a viewport width of 1280px when browsing the web. At this size, the main content section is too small, making the code block very inconvenience to read, compared to the old docfx theme. Also images overflow and is overlap with the table of content.

Here is an example:

![image](https://user-images.githubusercontent.com/12182348/112437592-b4465700-8d79-11eb-9817-6342ae8ed05c.png)

Compared to the old package docs, which use the space a lot better, and I can read the code comfortably:

![image](https://user-images.githubusercontent.com/12182348/112437520-9ed12d00-8d79-11eb-9e19-fd88d09f4b9c.png)

**Comment by Briancoughlin** [comment]
Images do overlap with the MINI TOC , which is absent from the Main Unity Docs,  And we dont wrap code but maintain the formatting. This will come down to a user choice, do they like the Mini TOC/Non-wrapping of code or not. We may need more feedback on this Should be a question at one of our group talks 
.

**Comment by Briancoughlin** [comment]
![image](https://user-images.githubusercontent.com/76997526/112454572-bcd66780-8d50-11eb-99e3-4a597689ce20.png)
There isn't a large amount of real-estate size difference in the two pages  we can possibly tweak the Mini TOC width to match.

**Comment by LeLocTai** [comment]
I think the a big contributor is the left padding on the main section.

Regarding the images, as the new site support click to zoom, scaling them down to fit should work fine

**Comment by Briancoughlin** [comment]
we will take a look make some changes and then post images here to see if it helps.

**Comment by lkrell** [comment]
I noticed we need to tweak the article size for that div. I'll check it out and get it going! Thanks for the feedback!

**Comment by Briancoughlin** [comment]
This has been addressed in PR #117
