### ISSUE TITLE
Child games

### ISSUE THREAD

**Issue by Tatogo86** [Unity-Technologies/com.unity.multiplayer.docs#1043]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.

**Steps to reproduce the behavior:**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior:**
Describe what you expected to happen.

**Screenshots**

**Desktop/Tablet/Smartphone (please complete the following information):**

**Additional info:**

**Comment by s-omeilia-unity** [comment]
None of the required information was filled out and user provided no clarification. Closing.
