### ISSUE TITLE
Feedback for /docs/migration/migratingtomlapi.md

### ISSUE THREAD

**Issue by lkrell** [Unity-Technologies/com.unity.multiplayer.docs#105]
**Provide Feedback on Docs**
Review code samples for MLAPI tabs and make sure the postfix is applied correctly.
Per Harrier in Discord.

For example 
![image](https://user-images.githubusercontent.com/76010626/112494602-30787480-8d51-11eb-9146-8cda7faf0ab8.png)

**Comment by Cosmin-B** [comment]
Posting here what I've mentioned on Discord: "the function signature in the new MLAPI release would be FunctionNameServerRpc or FunctionNameClientRpc for Server & Client RPC's"

**Comment by lkrell** [comment]
Updated! And merged. Site will be updated today
