### ISSUE TITLE
Feedback for docs/learn/bitesize/bitesize-spaceshooter.md

### ISSUE THREAD

**Issue by natebursch** [Unity-Technologies/com.unity.multiplayer.docs#1051]
https://docs-multiplayer.unity3d.com/netcode/current/learn/bitesize/bitesize-spaceshooter/#:~:text=introduces%20more%20latency.-,Player%20Health%E2%80%8B,%7B%0A%20%20%20%20if%20(NetworkManager.Singleton.IsServer%20%3D%3D%20false),-See%20full%20example

This is regarding player health.

The example doesn't relate to the text.

**Comment by s-omeilia-unity** [comment]
@fernando-cortez or @LPLafontaineB Could you double-check this for me?
