### ISSUE TITLE
Feedback for transport/transport-2-0-0.md

### ISSUE THREAD

**Issue by ezoray** [Unity-Technologies/com.unity.multiplayer.docs#1054]
The **Unity Transport** link is broken. Actually it's broken in all the release note pages although I'd imagine only this page and transport-1-0-0.md are still relevant.

**Comment by s-omeilia-unity** [comment]
Building to live now with this PR: https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/1070
