### ISSUE TITLE
Feedback for docs/tutorials/get-started-with-ngo.md Link is broken

### ISSUE THREAD

**Issue by Typhereus** [Unity-Technologies/com.unity.multiplayer.docs#1057]
Link is broken at line which describes: Launch the client and server together in a terminal, as shown in [Testing the command line helper](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/get-started-ngo/command-line-helper/).

**Comment by s-omeilia-unity** [comment]
Building to live now with this PR: https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/1070
