### ISSUE TITLE
Feedback for tools/release-1.0.0.md -> Dead Link

### ISSUE THREAD

**Issue by Reag** [Unity-Technologies/com.unity.multiplayer.docs#1064]
Link to https://docs-multiplayer.unity3d.com/releases/tools/network-simulator.md/ is dead, from line 

```For more information, see the [Network Simulator documentation](https://docs-multiplayer.unity3d.com/releases/tools/network-simulator.md/).```

In the release notes for 1.1.0

**Comment by s-omeilia-unity** [comment]
Building to live now with this PR: https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/1070
