### ISSUE TITLE
Feedback for docs/about.md

### ISSUE THREAD

**Issue by seanfcastillo** [Unity-Technologies/com.unity.multiplayer.docs#1076]
```
Netcode supports the following versions:

Unity 2020.3, 2021.1, 2021.2, 2021.3, and 2022.
Mono and IL2CPP
```

This is unclear / I have a question about what versions of 2022 are supported.. 2022.1 or 2022.2 ?

**Comment by s-omeilia-unity** [comment]
Hi @seanfcastillo,
All 2022 versions are supported. I will make an update to the docs to make that more clear.
