### ISSUE TITLE
Dilmers tutorials link results in 404

### ISSUE THREAD

**Issue by jdbhartley** [Unity-Technologies/com.unity.multiplayer.docs#1087]
https://docs-multiplayer.unity3d.com/netcode/current/learn/dilmer/dilmer-video.md/

Is a link on the main page, you click it and a 404 page pops up 
![image](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/assets/24490599/bd890bd1-2c82-4abb-9a2b-c9acf606df35)

**Comment by schgames** [comment]
Still not working. This is a missing tutorial or a deprecated one?

**Comment by jabbacakes** [comment]
Not sure when this was fixed, but it looks like it's working now, so closing this issue.
