### ISSUE TITLE
Broken links in docs/advanced-topics/message-system/rpc-params.md

### ISSUE THREAD

**Issue by zachstronaut** [Unity-Technologies/com.unity.multiplayer.docs#1094]
Links are broken to ServerRpcParams/ClientRpcParams docs on this page:
https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/message-system/rpc-params/

For example, this broken link:
https://docs-multiplayer.unity3d.com/netcode/current/api/Unity.Netcode.ServerRpcParams

**Comment by Andrew-Nekowitsch** [comment]
It's worth noting that the link is broken in multiple places and I can't seem to find the correct link.

https://github.com/search?q=repo%3AUnity-Technologies%2Fcom.unity.multiplayer.docs%20https%3A%2F%2Fdocs-multiplayer.unity3d.com%2Fnetcode%2Fcurrent%2Fapi%2FUnity.Netcode.ServerRpcParams&type=code

**Comment by zachstronaut** [comment]
see also: https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/issues/2673
