### ISSUE TITLE
Typo in the picture

### ISSUE THREAD

**Issue by KumoKyaku** [Unity-Technologies/com.unity.multiplayer.docs#1097]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.
https://docs-multiplayer.unity3d.com/netcode/current/learn/dealing-with-latency/
![image](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/assets/15962980/cb60059a-ce82-405c-ac2e-4a7a35b7810a)

**Steps to reproduce the behavior:**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior:**
Describe what you expected to happen.

**Screenshots**

**Desktop/Tablet/Smartphone (please complete the following information):**

**Additional info:**

**Comment by s-omeilia-unity** [comment]
@jilfranco-unity Do you have access to these images still to make a quick update to the 'NetVar' outlined in the image?

**Comment by jilfranco-unity** [comment]
> @jilfranco-unity Do you have access to these images still to make a quick update to the 'NetVar' outlined in the image?

Yes! :) Upon investigation, I've spotted similar typos in other diagrams as well. I've made a PR for them [here](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/1099)

**Comment by s-omeilia-unity** [comment]
Completed and pushing to live
