### ISSUE TITLE
Feedback for docs/about.md

### ISSUE THREAD

**Issue by Xtarii** [Unity-Technologies/com.unity.multiplayer.docs#1104]
I like the simple networking netcode adds, but ClientNetworkTransform should be a default.

Why do I have to install netcode, in a project and just to add movement, I need to add extra packages. Normally a multiplayer game allows all players to move, not one

**Comment by jabbacakes** [comment]
I've provided this feedback to our internal dev team. Thanks for contributing! ^_^
