### ISSUE TITLE
Feedback for /docs/migration/migratingtomlapi.md

### ISSUE THREAD

**Issue by schraf** [Unity-Technologies/com.unity.multiplayer.docs#111]
The first sentence under the "Current limitations" section reads:

> Review the following limitations for upgrade and migrations from previous versions of MLAPI to Unity MLAPI

and I believe you intended it to be

> Review the following limitations for upgrade and migrations from previous versions of **UNet** to Unity MLAPI

**Comment by lkrell** [comment]
Getting this updated, thanks!

**Comment by lkrell** [comment]
Fixed! The update will be production today.
