### ISSUE TITLE
Feedback for docs/advanced-topics/message-system/serverrpc.md

### ISSUE THREAD

**Issue by OsmarBriones** [Unity-Technologies/com.unity.multiplayer.docs#1112]
In the line:

    if (NetworkManager.ConnectedClients.ContainsKey(OwnerClientId))

I don't understand where the OwnerClientId comes from, in the other examples the parameter used inside the method ContainsKey is declared before, I believe this is a little issue.

**Comment by jabbacakes** [comment]
This is explained in the best practice box on this page, but to summarise: it can be a security risk to send client IDs as parameters from clients to the server.

**Note:** `ServerRpc` is now deprecated and using the universal `Rpc` attribute is now what's recommended. See [this documentation page](https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/message-system/rpc/).
