### ISSUE TITLE
Feedback for docs/advanced-topics/serialization/serialization-arrays.md

### ISSUE THREAD

**Issue by broken-ice-ice** [Unity-Technologies/com.unity.multiplayer.docs#1116]
"Arrays of C# primitive types, like int[], and Unity primitive types, such as Vector3, are serialized by built-in serialization code. Otherwise, any array of types that aren't handled by the built-in serialization code, such as string[], needs to be handled through a container class or structure that implements the INetworkSerializable interface."(https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/serialization/arrays/)

"C# Primitive types will be serialized by built-in serialization code. These types include bool, char, sbyte, byte, short, ushort, int, uint, long, ulong, float, double, and string."(https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/serialization/cprimitives/)

The first part writes that arrays of C# primitive types can be serialized while the string[] can not. The second part recognizes the string as a C# primitive type. This confused me as I am new.

**Comment by jabbacakes** [comment]
Addressed in PR #1253

**Comment by jabbacakes** [comment]
Updates made, will be published soon.
