### ISSUE TITLE
Incorrect MLAPI example in Replace NetworkManager section of /docs/migration/migratingtomlapi.md

### ISSUE THREAD

**Issue by schraf** [Unity-Technologies/com.unity.multiplayer.docs#112]
The MLAPI example calls NetworkingManager.Singleton methods where it should be NetworkManager.Singleton

**Comment by Briancoughlin** [comment]
Work being completed in PR #115 can be closed when PR is merged

**Comment by lkrell** [comment]
Completed, update will be live today. Thank you!
