### ISSUE TITLE
Feedback for docs/tutorials/testing/testing_locally.md - dodgy grammar on line 15

### ISSUE THREAD

**Issue by 11BelowStudio** [Unity-Technologies/com.unity.multiplayer.docs#1124]
Line 15 has some dodgy grammar - the usage of "it's" in this situation, whilst arguably grammatically correct (used as a contraction of "it is"), seems rather questionable in context ('*...and the way to do it's by creating Player Builds*') and just feels unpleasant to read.

This is a very simple issue; the way to fix it's by replacing the *it's* in that sentence with *it is* (or *this is*, to be on the safe side). ~~And yes, that sentence was mildly painful for me to write, thank you for asking~~. See #1123 for PR.

**Comment by jabbacakes** [comment]
Fixed as part of related PR. Thanks for contributing ^_^
