### ISSUE TITLE
Feedback for docs/advanced-topics/networktime-ticks.md

### ISSUE THREAD

**Issue by OsmarBriones** [Unity-Technologies/com.unity.multiplayer.docs#1126]
Link missing in NetworkTimeSystem Configuration:

See the API docs (TODO LINK) for information about the properties which can be modified.

**Comment by jabbacakes** [comment]
This issue has been fixed! Thank you for reporting it ^_^

See here: https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/networktime-ticks/#networktimesystem-configuration
