### ISSUE TITLE
Feedback for docs/basics/networkobject.md

### ISSUE THREAD

**Issue by schouffy** [Unity-Technologies/com.unity.multiplayer.docs#1148]
"The order of networked objects matters. Make sure to load any NetworkBehaviour components before the Network Object component on the GameObject."
Is that the order of the scripts in the inspector? The execution order in project settings?

Ownership:
"Either the server (default) or any connected and approved client each NetworkObject."
This sentence makes no sense.

**Comment by jabbacakes** [comment]
The wording on this page has been updated now. Thank you for raising the issue!
