### ISSUE TITLE
Overall Feedback - missing documentation for latest actual release - 1.7.1??

### ISSUE THREAD

**Issue by seanfcastillo** [Unity-Technologies/com.unity.multiplayer.docs#1157]
I just followed the directions on https://docs-multiplayer.unity3d.com/netcode/current/installation/ to install the package. When doing so, Unity installs the latest version in Package Manager, which is 1.7.1, released on November 24th, 2023. 

Why does the documentation only go to 1.6.0?
https://docs-multiplayer.unity3d.com/netcode/current/about

^here, "current" should refer to the latest released version, right? Is 1.7.1 a beta or something? Where is the documentation? Why is 1.6.0 considered the latest version?

Apologies if I somehow downloaded a beta version but there is no indication that 1.7.1 is not a full release.

**Comment by jabbacakes** [comment]
There was a bit of a delay between updating the docs after package release, due to staffing issues. It's all up to date now though!
