### ISSUE TITLE
Not a bug, but outdated steps to add networked prefabs

### ISSUE THREAD

**Issue by MagicBOTAlex** [Unity-Technologies/com.unity.multiplayer.docs#1166]
**Describe the bug:**
Missing some steps to add networked prefabs to networkmanager

**Steps to reproduce the behavior:**
https://docs-multiplayer.unity3d.com/netcode/current/basics/object-spawning/

**Expected behavior:**
The outdated version would work, but no.

**Screenshots**
![image](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/assets/44818698/987af347-49fd-4408-b7ab-84d502ad09ce)

**Desktop/Tablet/Smartphone (please complete the following information):**
- Unity 2022.3.11f1
- Netcode: 1.6

**Additional info:**
I have created a pull request, which I'll attach this issue to in a sec.

**Comment by jabbacakes** [comment]
Thanks for raising this issue, and a PR as well! It'll be updated on the live site soon.
