### ISSUE TITLE
Feedback for /docs/mlapi-basics/object-visibility.md

### ISSUE THREAD

**Issue by davidrochin** [Unity-Technologies/com.unity.multiplayer.docs#118]
**Provide Feedback on Docs**
I think you should clearly define what "making an object invisible" really is.

**Specific page:**
https://docs-multiplayer.unity3d.com/docs/mlapi-basics/object-visibility

**Comment by Briancoughlin** [comment]
Can you give more details on what you mean by clearly defining, what are we missing and what would you like us to give more detail on

**Comment by Briancoughlin** [comment]
This is now on the backlog to be done thanks for your contribution

**Comment by s-omeilia-unity** [comment]
Related issue: #205

**Comment by s-omeilia-unity** [comment]
Addressed with this PR building live now: https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/657
