### ISSUE TITLE
Enable setting NetworkVariable with&without invoking OnValueChanged.

### ISSUE THREAD

**Issue by babaq** [Unity-Technologies/com.unity.multiplayer.docs#1185]
**Is your feature request related to a problem? Please describe.**
The default behavior of updating `NetworkVariable` was that the new value should be different than old value, but sometimes we want the `OnValueChanged` to be invoked no matter it's same or not. And in another case, we want to set `NetworkVariable` value without invoking `OnValueChanged`.

**Describe the solution you would like:**
Add a member function:
```csharp
public void SetValue<T>(T value, bool notify)
```
`notify==true` means no matter whether new value equals old value, we always invoke `OnValueChanged`.
`notify==false` means no matter whether new value equals old value, we don't invoke `OnValueChanged`.

**Comment by jabbacakes** [comment]
Thank you for making this feature request ^_^ I've forwarded it to the development team to consider.
