### ISSUE TITLE
Spawn NetworkPrefab as a child of Scene NetworkObject make the object jump out of the hierarchy as a sibling

### ISSUE THREAD

**Issue by babaq** [Unity-Technologies/com.unity.multiplayer.docs#1188]
**Describe the bug:**
spawning a network object that is the child of another network object, make it jump out of the hierarchy as a sibling.

**Steps to reproduce the behavior:**
1
```csharp
var go = GameObject.Instantiate(prefab, parent)
```
here parent is a scene defined network object.
2
```csharp
go.GetComponent<NetworkObject>().Spawn(true);
```
3
the `go` should be a child of parent, but now it is at the same level as a sibling of parent.

**Expected behavior:**
without spawning, the `go` is correctly added as a child of parent. but spawning make it jump out as a sibling of parent.

**Desktop/Tablet/Smartphone (please complete the following information):**
 - OS: win10
 - Unity: 2023.3.0b4
 - Netcode: 1.7.1

**Comment by jabbacakes** [comment]
Thanks for raising this bug! I've forwarded it to the development team so they can address it in the code.

**Comment by NoelStephensUnity** [comment]
As a side note:
[You can only parent a spawned object and cannot spawn post-parenting.](https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/networkobject-parenting/#only-spawned-networkobjects-can-be-parented).
The default action when you perform invalid parenting is to set the root as the parent.
