### ISSUE TITLE
Feedback for docs/tutorials/testing/testing_with_artificial_conditions.md

### ISSUE THREAD

**Issue by Dark-Griffin** [Unity-Technologies/com.unity.multiplayer.docs#1212]
The links for [Unity Transport - Simulator Tools](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/testing/testing_with_artificial_conditions/#unity-transport---simulator-tools) actually just open this same page again.  In Microsoft Edge, I tried new tab, Control F, everything I could think of, that header is not in the page anymore.  So, throughout the document it keeps saying "use this" while not actually giving any info where or what that tool is.

page is this one: https://docs-multiplayer.unity3d.com/netcode/current/tutorials/testing/testing_with_artificial_conditions/  Though I am sure there might be other broken links too, since this tool is mentioned throughout the multiplayer testing docs.

I searched the docs manually by keywords, and found this page instead:
https://docs-multiplayer.unity3d.com/tools/current/tools-network-simulator/

I'd suggest redoing the links to point to that page instead.  It was really confusing to just be directed in circles.  Would save others my 10 min of trying to google such a generic name when our glorious AI search overlord keeps redirecting to third party tools instead.

**Comment by jabbacakes** [comment]
Thanks for reporting, I'll get this fixed. All hail our glorious AI overlords 🙏

**Comment by jabbacakes** [comment]
Links fixed, will publish the docs now to get the updates live. Thanks again ^_^
