### ISSUE TITLE
Feedback for docs/basics/object-spawning.md

### ISSUE THREAD

**Issue by Libberator** [Unity-Technologies/com.unity.multiplayer.docs#1218]
The provided link for the text "Learn more about In-Scene Placed NetworkObjects" is to a broken URL page: https://docs-multiplayer.unity3d.com/netcode/current/basics/object-spawning/scenemanagement/inscene-placed-networkobjects/

The correct URL is:
https://docs-multiplayer.unity3d.com/netcode/current/basics/scenemanagement/inscene-placed-networkobjects/

**Comment by jabbacakes** [comment]
This has been fixed and published to the live site. Thank you for raising the issue ^_^
