### ISSUE TITLE
Feedback for docs/tutorials/get-started-with-ngo.md

### ISSUE THREAD

**Issue by xsraut** [Unity-Technologies/com.unity.multiplayer.docs#1237]
After following the exact steps given in "Get started with Netcode for GameObjects", the script "RpcTest.cs" gives error at line 14 and 24 stating that RpcAttribute is an abstract class and SendTo does not exist in current context.

**Comment by ShadauxCat** [comment]
Hi @xsraut,

From what you are saying, I think you are using an older version of Netcode for GameObjects. `RpcAttribute` was abstract prior to version 1.8.0, when we introduced universal RPCs and upgraded it to a full class. If you can, please upgrade to the current version of Netcode for GameObjects; if not, make sure you are referencing the documentation for the version you have installed.
