### ISSUE TITLE
OnGainedOwnership and OnLostOwnership

### ISSUE THREAD

**Issue by kevincastejon** [Unity-Technologies/com.unity.multiplayer.docs#1255]
**What documentation page is missing?**
The page is not missing but the description of these two methods are unclear and wrong.

**(optional) Provide us with more details**

**- OnGainedOwnership** 
The current documentation description says that the method is called when the local client gained ownership, but is actually called server-side when any client gain ownership, even remote ones.

**- OnLostOwnership** 
The current documentation description says that the method is called when "we loose ownership", which is unclear and inconsistent with the above method description, but is actually called server-side when any client lost ownership, even remote ones.

**Comment by jabbacakes** [comment]
This has been fixed in the two linked PRs. The changes won't be visible in the public API docs until the next release of the package, however.
