### ISSUE TITLE
Feedback for docs/learn/rpcvnetvar.md

### ISSUE THREAD

**Issue by bertrand-toca** [Unity-Technologies/com.unity.multiplayer.docs#1256]
The following links are broken:
[Remote Procedure Call](https://docs-multiplayer.unity3d.com/netcode/current/learn/advanced-topics/messaging-system/) and  [NetworkVariable](https://docs-multiplayer.unity3d.com/netcode/current/learn/basics/networkvariable/)

**Comment by bertrand-toca** [comment]
And hi Vic! :)

**Comment by jabbacakes** [comment]
Surprise, these are my docs now! Also @Vic-Cooper says hi ^_^

**Comment by Vic-Cooper** [comment]
HI BERTRAND, MISS YOU, HOPE YOU'RE DOING WELL! 

(shouting from the other desk in the office).

**Comment by bertrand-toca** [comment]
Oh hi! Nice bumping into you both :D 
I hope you're both doing great!
And amazing turnaround time on this bug report too!

**Comment by jabbacakes** [comment]
Team work makes the dream work 🤜 🤛 

Links fixed in PR that was just merged. Will kick off the publishing job now ^_^
