### ISSUE TITLE
NetworkBehaviour introduction paragraph contains redundancy

### ISSUE THREAD

**Issue by CodeSmile-0000011110110111** [Unity-Technologies/com.unity.multiplayer.docs#1276]
First paragraph on the [NetworkBehaviour page](https://docs-multiplayer.unity3d.com/netcode/current/basics/networkbehavior/) reproduced in full:

> NetworkBehaviours can use NetworkVariables and RPCs to synchronize state and send messages over the network. **to replicate any netcode aware properties or send/receive RPCs a GameObject must have a** [**NetworkObject component**](https://docs-multiplayer.unity3d.com/netcode/current/basics/networkobject/) **and at least one NetworkBehaviour component.** A NetworkBehaviour requires a NetworkObject component on the same relative GameObject or on a parent of the GameObject with the NetworkBehaviour component assigned to it. If you add a NetworkBehaviour to a GameObject that does not have a NetworkObject (or any parent), then Netcode for GameObjects will automatically add a NetworkObject component to the GameObject in which the NetworkBehaviour was added.

2nd sentence should be deleted. It does not add information the other sentences don't already contain, in fact it contradicts somewhat in that it implies that the NetworkObject has to be on the same GameObject when it can also be on a parent.

**Comment by jabbacakes** [comment]
We recently reworked the NetworkBehaviour page as part of PR #1260, which has now been published [here](https://docs-multiplayer.unity3d.com/netcode/current/basics/networkbehavior/). I think the changes to the introductory section made in that PR resolve the duplication issue you've pointed out here, so I'm going to close this issue as solved.

Thanks for raising it and contributing to the docs ^_^ If you have any further comments, feel free to reopen the issue or leave some additional comments.
