### ISSUE TITLE
Unclear: Start NetworkManager in Awake can have "undesirable results"

### ISSUE THREAD

**Issue by CodeSmile-0000011110110111** [Unity-Technologies/com.unity.multiplayer.docs#1277]
The DANGER box under [NetworkManager here](https://docs-multiplayer.unity3d.com/netcode/current/components/networkmanager/#starting-a-server-host-or-client) is missing information:

> DANGER
> Don't start a NetworkManager within a NetworkBehaviour's Awake method as this can lead to undesirable results depending upon your project's settings!

First: "undesirable results" sounds pretty harmless. This should at least hint at the possible issues.

Then it should also indicate what project settings might affect this. Are these NGO specific settings, or script execution order, or something else?

**Comment by jabbacakes** [comment]
We've added more detail about starting NetworkManagers in the linked PR. I'm gonna close this issue as complete now, but feel free to reopen it/leave more comments if you still want more information.

Thanks for raising the issue and engaging with improving the docs, we really appreciate it ^_^
