### ISSUE TITLE
Feedback for /docs/learn/rpcnetvarexamples.md

### ISSUE THREAD

**Issue by AlanPereira-AQUIRIS** [Unity-Technologies/com.unity.multiplayer.docs#130]
![image](https://user-images.githubusercontent.com/69805538/113932575-25e6c200-97ca-11eb-9c06-973c7776ae9c.png)

Would here be NetworkVariable, instead of RPC. (last sentence), right?

**Comment by Briancoughlin** [comment]
can be closed once associated PR is merged

**Comment by Briancoughlin** [comment]
text updated in associated PR request #131
