### ISSUE TITLE
Feedback for docs/basics/scenemanagement/inscene-placed-networkobjects.md - Broken link

### ISSUE THREAD

**Issue by Thomas-Jonckheere** [Unity-Technologies/com.unity.multiplayer.docs#1303]
The hyperlinks do not work in these sentences:

> Referring back to the [Complex In-Scene NetworkObject Managers](https://docs-multiplayer.unity3d.com/netcode/current/basics/scenemanagement/inscene-placed-networkobjects/inscene-placed-networkobjects/#complex-in-scene-networkobjects), it's recommended to use dynamically spawned NetworkObjects if you are planning on destroying the object when it's de-spawned. However, if either de-spawning but not destroying or using the hybrid approach ([discussed earlier on this page](https://docs-multiplayer.unity3d.com/netcode/current/basics/scenemanagement/inscene-placed-networkobjects/inscene-placed-networkobjects/#a-hybrid-approach-example)) (dynamically spawned) don't appear to be options for your project's needs, then there are only two other possible (but not recommended) alternatives:

> These two "alternatives" aren't recommended but worth briefly exploring to better understand why we recommend using a [**non-pooled hybrid approach]**(https://docs-multiplayer.unity3d.com/netcode/current/basics/scenemanagement/object-spawning/#dynamic-spawning-non-pooled) or just not destroying the in-scene placed NetworkObject when de-spawning it. The time spent implementing and possibly debugging either of the two above not recommended approaches will far exceed the time spent implementing one of the recommended approaches.

Last one should be: 
https://docs-multiplayer.unity3d.com/netcode/current/basics/object-spawning/#dynamic-spawning-non-pooled

**Comment by jabbacakes** [comment]
Links fixed, thanks for raising the issue! ^_^
