### ISSUE TITLE
Feedback for docs/learn/distributed-authority-quick-start.md

### ISSUE THREAD

**Issue by davidjsap** [Unity-Technologies/com.unity.multiplayer.docs#1305]
Hello, I'm following these steps to try out distributed authority, but the ConnectionManager script throws an error: **Assets\_Project\Multiplayer\ConnectionManager.cs(94,15): error CS1061: 'SessionOptions' does not contain a definition for 'WithDistributedConnection' and no accessible extension method 'WithDistributedConnection' accepting a first argument of type 'SessionOptions' could be found (are you missing a using directive or an assembly reference?)**

I have otherwise followed the tutorial exactly. Any help would be appreciated.
Thanks!

**Comment by jabbacakes** [comment]
This issue was fixed in PR #1304 - if you use `WithDistributedAuthorityNetwork` instead of `WithDistributedConnection`, you should be all good ^_^

I'm closing this issue as resolved, but if you continue to have problems feel free to reopen it/ask further questions.
