### ISSUE TITLE
HelloWorldManagger.cs  NetworkManager.Singleton missing.

### ISSUE THREAD

**Issue by JacobChrist** [Unity-Technologies/com.unity.multiplayer.docs#1318]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.

The HelloWorldManagger.cs script given on this page is using a private NetworkManager m_NetworkManager; variable but the description below it is using a NetworkManager.Singleton in place of m_NetworkManager.

https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/main/docs/tutorials/get-started-with-ngo.md

This appears to be in error.

**Comment by jabbacakes** [comment]
Thanks for flagging this! I've updated all of the scripts on this page to use `m_NetworkManager`, as intended.
