### ISSUE TITLE
Multiplayer Play Mode and git Submodules

### ISSUE THREAD

**Issue by Paolofix21** [Unity-Technologies/com.unity.multiplayer.docs#1325]
Hello,

I wanted to try this new feature which seemed nice in theory, but I smashed my head against a wall discovering that it has **issues** with **packages** that are installed **as git submodules**.

My project is a local repository with some packages installed as submodules, and when I try to enable a virtual player, it logs errors regarding those packages, specifically:
```console
An error occurred while resolving packages:
Project has invalid dependencies:
    Camera System: Package name 'Camera System' is invalid.
    Character Controllers: Package name 'Character Controllers' is invalid.
    Izinspector: Package name 'Izinspector' is invalid.

Click on Retry to relaunch Unity and reopen your project.
```

Clicking on _Continue_ or _Retry_ doesn't solve it.

I'm not sure whether the issue is with embed packages in general, or only with those that are git submodules.

While you may fix it (or may not most probably if this package ends up like Kinematica) is there a **temporary solution** that I can try?

Kind regards.

**Comment by cdmazom** [comment]
Hello!

What version are you using? We recently fixed an issue with embed packages that sounds very similar. That's in `1.3.0-pre.1` and `1.2.2`.

**Comment by johann-r-unity** [comment]
Hi @Paolofix21 , as Cristian mentioned this issue has likely been resolved. I suggest to use Multiplayer Playmode `1.3.0` as this will be the supported version for Unity 6.0 . 
I am going to close this issue, feel free to re-open it if your problem was not addressed.
