### ISSUE TITLE
Feedback for docs/learn/distributed-authority-quick-start.md

### ISSUE THREAD

**Issue by hanghoo** [Unity-Technologies/com.unity.multiplayer.docs#1342]
Hello there, when I want to set up Distributed Authority, I cannot find the Network Settings and Network Topology property to set it. Do you have any suggestions? Thank you very much.

**Comment by mcanfield-unity** [comment]
Have you installed Unity 6 and Netcode for GameObjects 2.0.0 ? You will not see this setting on the `NetworkManager` for the 1.x line.

**Comment by jabbacakes** [comment]
It's been a while since we've had any activity on this issue, so I'm going to close it as stale. Please reopen it if you need more help!
