### ISSUE TITLE
Bug with link to  First Steps with MLAPI  / Feedback for /docs/tutorials/helloworldintro.md

### ISSUE THREAD

**Issue by asyasmi** [Unity-Technologies/com.unity.multiplayer.docs#135]
https://docs-multiplayer.unity3d.com/docs/getting-started/about-mlapi/index.html -> Press the First Steps with MLAPI -> https://docs-multiplayer.unity3d.com/docs/getting-started/tutorials/helloworldintro is opened in the same tab, Page not found 
 (Chrome). 

If I open the link in a new tab it opens the correct page.

**Comment by Briancoughlin** [comment]
OK this one is being weird. i can reproduce it but there isn't a good reason why its doing it the link isn't resolving correctly unless its in a tab and even then it might work in frame. Will do more investigation

**Comment by Briancoughlin** [comment]
should now be fixed, forced a target on the link which seems to solve the issue
