### ISSUE TITLE
Feedback for /docs/advanced-topics/messaging-system.md

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [Unity-Technologies/com.unity.multiplayer.docs#137]
Hi
Please either add an additional page that has a messaging example and compares custom messages and NetworkManager messages or simply provide an example here.

**Comment by Briancoughlin** [comment]
HIya, going to ask a bit more from you so we have some basic syntax on messaging-system.md page, then there is a section of RPC's which goes into more detail. there is also a section in Learn on RPC's v NetworkVariables. are we missing something specific or is it just a more detailed exexample that you would like to see?

**Comment by ashkan-saeedi-mazdeh** [comment]
@Briancoughlin  Something in the messages.md or another page which clarifies this part of the API reference docs 
![image](https://user-images.githubusercontent.com/5682459/115990260-7ab27700-a5d7-11eb-9ab2-0b7c20d62d1c.png)

Questions which come to mind:

- How to send messages using `NetworkManager`? how to do it using `CustomNetworkMessages`?
None of these are never described in the doc.
- what are the performance characteristics of these two? what is sent on the wire for them? a comparison to uNet's messages which were being identified using a short message code is appreciated too.

**Comment by ashkan-saeedi-mazdeh** [comment]
It is really great that messages are flexible and we don't have to send named ones and unnamed ones with custom protocol can be sent.
 
 The fact that visibility check is a method with no abstraction on top and we are free to form messages that we want in the way we want makes this really mid-level and I hope we can scale it to high numbers in the future

**Comment by lkrell** [comment]
Thanks for the feedback! We'll get further information added to the docs for this!

**Comment by s-omeilia-unity** [comment]
Related issues: #391, #437

**Comment by s-omeilia-unity** [comment]
Custom messages are covered here: https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/message-system/custom-messages/index.html
