### ISSUE TITLE
Feedback for /docs/components/networkanimator.md

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [Unity-Technologies/com.unity.multiplayer.docs#138]
Please specify in this page that usually games don't synchronize animation state and instead derive it from other synchronized state like position and other attributes/events.
I don't know of any commercial game which wastes bandwidth to serialize animations. I'm sure you can find examples but still it's good to state this in here.

Disclaimer I haven't checked BossRoom or its documentation, You might have said it there but I probably it is equally important or even more important to state it here just like you stated the fact that most games need to write their own transform sync code in the page for that component. This is probably ok for prototying animation synchronization but not for anything more IMHO We did not have a similar component for uLink even for prototyping and we only had 5 types of character synchronization  scripts for different types of games based on rigidbodies, character controllers, transforms and ... we had multiple ones per component for games which have gravity and jumping and for those which don't and that was it.

**Comment by lkrell** [comment]
Thanks for the feedback! Checking into the animator info and your comments to see what we can add, best practices, recommendations.

**Comment by Briancoughlin** [comment]
This is now on the backlog to be done thanks for your contribution

**Comment by s-omeilia-unity** [comment]
Addressed with PR #665 and pushing to live now
