### ISSUE TITLE
Feedback for /docs/mlapi-basics/object-spawning.md

### ISSUE THREAD

**Issue by fachryip** [Unity-Technologies/com.unity.multiplayer.docs#141]
Hello

In Scene Objects section it is said that

> Any objects in the scene with NetworkObject components will get automatically replicated by MLAPI. There is no need to manually spawn them.

This is not entirely accurate, because **only active** NetworkObject that will get automatically replicated by MLAPI. Inactive NetworkObject will not be replicated, thus didn't have NetworkObjectId even after you enabled it in the middle of the game. 

See this issue for more information [https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi/issues/730](url)

Thank you

**Comment by Briancoughlin** [comment]
changes now  on the site
