### ISSUE TITLE
Feedback for /docs/tutorials/helloworldparttwo.md

### ISSUE THREAD

**Issue by JohnMiki47** [Unity-Technologies/com.unity.multiplayer.docs#144]
Hello, I am configuring Hello World project according to this tutorial, but I am little bit confused by the result.
After finishing the tutorial:
- Start play mode
- Start as host in one instance, start as client in another instance
- Connecting as client produces following warning in the console : "Only the owner can invoke a ServerRpc that requires ownership!"

However, as stated by docs:
If we are a client, we call a server RPC. This server RPC simply sets the position NetworkVariable on the server's instance of this player...

So, can a client call a server RPC or only the owner?

**Comment by JohnMiki47** [comment]
Maybe the solution is as simple as changing this code section:
`if (NetworkManager.Singleton.IsServer)
            {
                var randomPosition = GetRandomPositionOnPlane();
                transform.position = randomPosition;
                Position.Value = randomPosition;
            }
            else
            {
                SubmitPositionRequestServerRpc();
            }`
to this?
`if (NetworkManager.Singleton.IsServer)
            {
                var randomPosition = GetRandomPositionOnPlane();
                transform.position = randomPosition;
                Position.Value = randomPosition;
            }
            else if (IsLocalPlayer)
            {
                SubmitPositionRequestServerRpc();
            }`

Or am I not understanding it correctly?

Thanks for the reply.

**Comment by Briancoughlin** [comment]
@Cosmin-B do we need to add some clarification to the guide here or is their an issue with the code as written?

**Comment by Alphamplyer** [comment]
I had the same warning ("Only the owner can invoke a ServerRpc that requires ownership!").
The solution is simple. This warning is called when I started the client side. Just add this line to the _HelloWorldPlayer.cs_ script in the _NetworkStart_ Method :
```csharp
public override void NetworkStart()
{
	if (!IsOwner) return;
	Move();
}
```

When we start the client the NetworkStart Method is called on both instance of the player script (the host one and the client one).

**Comment by Briancoughlin** [comment]
THis is now in process and will be updated. Thanks for your contribution
