### ISSUE TITLE
feedback about missing info in the docs

### ISSUE THREAD

**Issue by ashkan-saeedi-mazdeh** [Unity-Technologies/com.unity.multiplayer.docs#154]
**Provide Feedback on Docs in general**
First of all thank you for the good job you guys are doing on the docs
There are concepts which are very well described in the doc and concepts which are not described. I haven't dogged deep into the source code yet so the answer to some of these might be obvious there but adding info in pages would be very helpful.

- The network time in network manager is not described anywhere? Is it working? how well does it sync? how much delta is common between client and server, can it move backwards, does it slow the game down when the error delta is huge?
- Sequencing properties of messages are not described? Are all unreliable messages unordered and all reliable ones ordered? can we change this? concepts like fragmented channels of uNet for sending bigger messages are not described? While sending messages which are big using a RUDP library is not a good practice, it is a good idea to describe the limitations and features on these?
- Network config variables are not described? The best source for the uNet config was Alexey Abramychev's video at unite 16? please provide more complete info on that regard?
- should we use the low level transport for calculating delay between server and client?
- can we use secure communication in MLAPI or not if yes, how? can it be enabled on a per RPC basis?
- How does the library send messages? is it immediate? is it at the end of each frame? Can this be changed? Is there any behavior like `NetworkServer.sendDelay` in uNet which never should have been there IMO? I want to know if there is anything like that to set it to 0.
- Can we change the pool sizes for `NetworkConnection`, `NetworkBuffer` and related classes depending on our game's player count and message frequencies? If yes how?
- Any limits/benchmarks can be helpful because a blog post mentioned a 65 player limit without mentioning the throughput or the reasoning of that number.
- Can we listen to two transports for say webGL and UDP in a single server if yes how? in uNet we could do this using two `SimpleServer`s which one of them was added as external conneciton to `NetworkServer`. Is anything like that possible here? Do we have `NetworkClient` and `NetworkServer` classes here? I don't want to use the `NetworkManager` to be able to run multiple clients say for load testing or multiple servers so can listen to all clients on all platforms. how can I do that? I found out the answer to most of these or almost all of them by reading the source code but adding them to the docs is greatly appreciated.
Cheers

**Specific page:**
This is not anything specific to any page but a set of info missing from the pages

**About the site:**
A few new pages describing these unspecified parts of the documentation or modifying the current pages in a way that they describe these as well.

**Comment by ashkan-saeedi-mazdeh** [comment]
Also it is not described anywhere that IP and port should be set in the transport and how to disable script CRC mismatch. 

I could not find this CRC mismatch thing from all of the above stuff.

**Comment by Briancoughlin** [comment]
We have added this to our backlog and will be addressing this
