### ISSUE TITLE
Feedback for /docs/getting-started/index.md

### ISSUE THREAD

**Issue by ArturoNereu** [Unity-Technologies/com.unity.multiplayer.docs#155]
The first row of the  Unity MLAPI | Previous versions of MLAPI table has a hover effect. Probably unintentional from:

`<div class="table-columns-plain">`

**Comment by Briancoughlin** [comment]
I think it's a deliberate style choice. I will check with @lkrell

**Comment by lkrell** [comment]
If the hover over aspect is confusing, I can remove. It's a style choice for tables that may grow over time to show where you are when you hover.

**Comment by lkrell** [comment]
Tweaked and fixed, changes going live!
