### ISSUE TITLE
Feedback for /docs/tutorials/goldenpath.md

### ISSUE THREAD

**Issue by FocusJP** [Unity-Technologies/com.unity.multiplayer.docs#161]
Firstly, thanks so much for the documentation!  

I had weird behavior when connecting multiple clients.  After some head-scratching, I fixed by changing `IsClient` to `IsClient && IsOwner` in several places.  I realize multiple clients is not mentioned here, but figured people may want to try it, and this could avoid some confusion.

**Comment by Briancoughlin** [comment]
Thanks @FocusJP  for this feedback, I have some tweaks for the golden sample pages in progress and will try and find a good way to incorporate this into the updated docs.

**Comment by Briancoughlin** [comment]
WE are going to vcheck the code for the samples and see what we can do to make this better
