### ISSUE TITLE
Feedback for /docs/learn/getting-started-boss-room.md

### ISSUE THREAD

**Issue by CamAtlantic** [Unity-Technologies/com.unity.multiplayer.docs#164]
Hi folks, thanks for posting this!

I'm stuck trying to get the Boss Room project to open. It keeps complaining that I don't have git installed - I did before downloading, but did a fresh install just in case.

Is it looking for Git in a specific location? If so, can you let me know where it wants to be?

If this is meant for beginners, they might struggle ;)

Cheers & hope to hear from you soon,
Cam

I added the log btw
[Editor.log](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/files/6411433/Editor.log)

**Comment by lkrell** [comment]
Hi there! Sorry for the trouble you are having. 

For Git, if you have installed it, you may need to also fully restart your computer. I looked over the instructions and see we need to add that note to the instructions just in case. We've seen that sometimes restarting just Unity after an install does not always capture the Git install.

Try restarting the computer, then working with the instructions to add the project to the Unity Hub. Let me know if that works! And I'll get that note added to the page.

**Comment by Briancoughlin** [comment]
There is a note on the Install MLAPI page about this, because MLAPI is installed with BossRoom the note was not carried across. Good Spot @CamAtlantic

**Comment by lkrell** [comment]
Content going live!
