### ISSUE TITLE
Feedback for /docs/mlapi-api/introduction.md

### ISSUE THREAD

**Issue by ArturoNereu** [Unity-Technologies/com.unity.multiplayer.docs#165]
The `MLAPI.NetworkVariable.Collections` option on the menu of the left overlaps with the `>` character.

![image](https://user-images.githubusercontent.com/263776/116820469-f615aa80-ab3a-11eb-98b9-d42e8735e4f4.png)

**Comment by lkrell** [comment]
Thanks for the feedback, I'm working on a solution to make the sidebar navigation much better for the API section! I aim to have these updates published with versioning by May 7th.

**Comment by lkrell** [comment]
Content going live! Thanks!
