### ISSUE TITLE
Feedback for /docs/tutorials/helloworldintro.md

### ISSUE THREAD

**Issue by TelMonks** [Unity-Technologies/com.unity.multiplayer.docs#167]
I can not drag a prefab into the NetworkPrefabs inpector field. This happen with more than one 2020 or 2021 release. Attached image is from 2021.14.f1
![Screenshot 2021-05-03 110517](https://user-images.githubusercontent.com/85035/116893935-84536480-abff-11eb-8b26-af75ec39559d.png)

**Comment by Briancoughlin** [comment]
@TelMonks  Did you add the slot for the prefab its step 10 in the guide.

![image](https://user-images.githubusercontent.com/76997526/117116991-eb4f5580-ad86-11eb-8c0d-d31b77827f2d.png)

**Comment by TelMonks** [comment]
Yes, I did, but as you see, it can’t be done, it gets populated already. I tried deleting the network manager and adding it back : same thing happens.

**Comment by Briancoughlin** [comment]
Hmmm this may need a bit more investigation. I am not seeing that behaviour. I have just redone this and it seems to work fine (I am attaching my recording, hopefully it will work).  I can suggest a few things can you make the tab a bit wider to check what is in the 'NetworkPrefabs' field. ( just in case it's already there). then you can try removing all the existing entries by clicking the '-' and then re-adding one. 

![adding prefab](https://user-images.githubusercontent.com/76997526/117132015-25762280-ad9a-11eb-8f43-877be555d53c.gif)

**Comment by TelMonks** [comment]
That was the trick. If I make the window very large I can move something in there. Thanks for that. If you make yours more narrow you can probably reproduce what I saw.
Thanks!

**Comment by Briancoughlin** [comment]
Closed as user issue sorted
