### ISSUE TITLE
Feedback for /docs/tutorials/goldenpath.md

### ISSUE THREAD

**Issue by Wolframwow** [Unity-Technologies/com.unity.multiplayer.docs#168]
Sometimes on the Server the Player is not shown at the correct position (as it was static) but on the Client Side it works well => meaning that position is updated but it's not displayed. I solved this by reading the "NetworkTransform" script back to the Player and now the Player was also shown on the correct position also on the Server

**Comment by Briancoughlin** [comment]
Has been added to the backlog will be addressed in future update. Thanks for your contribution
