### ISSUE TITLE
Feedback for /docs/migration/installation.md

### ISSUE THREAD

**Issue by ShadowFox10** [Unity-Technologies/com.unity.multiplayer.docs#171]
The url does not work. It brings me to the 2d animation package instead.

**Comment by Briancoughlin** [comment]
@ShadowFox10   Sorry that you are having issues perhaps I can fix the issue can you let me know which URL is causing this issue on the page the install git one is "https://git-scm.com/". The one for installing MLAPI isn't a hyperlink you have to copy it into the 'Add package from git URL...' section of Unity Package manager, and is the path to the MLAPI git hub repo.

the last three go to pages within the Docs site itself.

**Comment by lkrell** [comment]
Hey @ShadowFox10  I added some additional info on https://docs-multiplayer.unity3d.com/docs/migration/install to help out!

The URL for step 5 you should hover over that code block, click the COPY button, and use that copied info to paste into the Unity Hub for the **Add package from git URL...** option. If you just click the URL or select and copy, it may do something funny. If you click the COPY button, it should work for you.

I added some info in the troubleshooting steps. If you can verify we can close as done or check further. Thanks!

**Comment by ShadowFox10** [comment]
thanks for the help! I managed to get MLAPI installed.
