### ISSUE TITLE
Feedback for /versioned_docs/version-0.1.0/mlapi-api/MLAPI.Transports.UNET.UnetTransport.md

### ISSUE THREAD

**Issue by NemoTheHero** [Unity-Technologies/com.unity.multiplayer.docs#178]
NetworkManager Script  is erasing value for NetworkTransport on Play

**Comment by LukeStampfli** [comment]
This is an MLAPI bug and not a documentation issue. Closing this. You can find the MLAPI issue [here](https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi/issues/716), upgrading Unity should fix it.
