### ISSUE TITLE
Feedback for /versioned_docs/version-0.1.0/migration/installation.md

### ISSUE THREAD

**Issue by longlongerbao** [Unity-Technologies/com.unity.multiplayer.docs#179]
Can't download project even with vpn working,errno 10054 and 443  
![3}_B 9%4EW%JPQI96 C47V1](https://user-images.githubusercontent.com/31440183/117605368-158b8380-b18a-11eb-8bff-715128267d16.png)
![R2AUYG 9ZU6L630}KV2F`LD](https://user-images.githubusercontent.com/31440183/117605383-1f14eb80-b18a-11eb-82b9-f1afb131de0f.png)

**Comment by longlongerbao** [comment]
> We're looking into this for you! We may contact for more information on your connection, etc.

Thank you very much!Can i provide a solution i found for this?I switch the vpn to america,and it's solved,but switch back to the hong kong the problems appears again.I guessed it's CDN or something?I'm not sure.

**Comment by lkrell** [comment]
Interesting, passing this along to folks looking into it. It may be an issue with routes and international. For now, I can add a note for users on VPNs.

**Comment by s-omeilia-unity** [comment]
Closed by MTTDOC-221
