### ISSUE TITLE
Feedback for /versioned_docs/version-0.1.0/migration/migratingtomlapi.md

### ISSUE THREAD

**Issue by nagylevi** [Unity-Technologies/com.unity.multiplayer.docs#195]
Under the NetworkStart Heading the sample code is wrong. There is a void keyword missing before the NetworkStart function name. See the image below. 
![Névtelen](https://user-images.githubusercontent.com/75484590/118807924-2f734780-b8a9-11eb-8c8d-9eae4e351d08.png)

**Comment by lkrell** [comment]
Thanks for the issue, checking into this to update!

**Comment by s-omeilia-unity** [comment]
Content does not appear to have been updated. Created Jira to track.

**Comment by Briancoughlin** [comment]
we are updating this, thanks for your contribution
