### ISSUE TITLE
Wrong indentation in a code section

### ISSUE THREAD

**Issue by peter-yeh** [Unity-Technologies/com.unity.multiplayer.docs#198]
**Steps to reproduce the behavior:**
1. Go to 'https://docs-multiplayer.unity3d.com/docs/tutorials/helloworldtwo/index.html#adding-editor-modes-to-hello-world'
2. The method `static void StatusLabels()` has wrong indentation

**Screenshots**
![image](https://user-images.githubusercontent.com/50769616/119246892-cac13100-bbb7-11eb-8776-2b6b5b182dd7.png)

**Desktop**
 - OS: Windows 10
 - Browser: chrome

**Comment by lkrell** [comment]
Checking thanks for the feedback!

**Comment by Briancoughlin** [comment]
Work on this is being carried out in the following branch

https://github.com/Unity-Technologies/com.unity.multiplayer.docs/tree/MTTDOC-244-Modularising-Golden-Path-to-enable-better-user-experience.

**Comment by Briancoughlin** [comment]
Thi has now been fixed  this issue can be closed when pr #208  is merged

Associated JIRA task is https://jira.unity3d.com/browse/MTTDOC-268
