### ISSUE TITLE
RPC Only usable on NetworkObject

### ISSUE THREAD

**Issue by LukeStampfli** [Unity-Technologies/com.unity.multiplayer.docs#206]
I got this feedback in the Forums about the RPC docs page and just wanted to capture it here:
<https://forum.unity.com/threads/how-should-i-send-a-player-disconnected-message-to-remaining-connected-clients.1116424/#post-7194889>

**Comment by Briancoughlin** [comment]
I will have a look at this and try and get something into make this clear, thanks Luke.

**Comment by Briancoughlin** [comment]
This is now on the backlog to be done thanks for your contribution
