### ISSUE TITLE
Feedback for /versioned_docs/version-0.1.0/advanced-topics/message-system/clientrpc.md

### ISSUE THREAD

**Issue by dbirman** [Unity-Technologies/com.unity.multiplayer.docs#214]
Either this page or the server page (https://docs-multiplayer.unity3d.com/docs/advanced-topics/message-system/serverrpc) really need to mention the RequireOwnership flag that can be set for Rpc functions. Otherwise the mysterious Rpc error message `Only the owner can invoke a ServerRpc that requires ownership!` appears and there is no information about how to fix it. 

Along with this the Error Message page mentions this error: https://docs-multiplayer.unity3d.com/docs/troubleshooting/errormessages/index.html but incorrectly explains that fixing it is done by returning out if you aren't the server. That's irrelevant here, since this has to do with incorrectly collecting a ServerRpc from a client that doesn't own the object that ServerRpc is attached to.

**Comment by Briancoughlin** [comment]
THis has been added to our backlog and will be updated

**Comment by s-omeilia-unity** [comment]
N/A for Client RPC page. Info available on Server RPC page. Closing.
