### ISSUE TITLE
Separate Client/Server projects

### ISSUE THREAD

**Issue by LukeStampfli** [Unity-Technologies/com.unity.multiplayer.docs#215]
I created this feature request due to demand in the [Unity Forums](https://forum.unity.com/threads/unity-mlapi-multiproject-structure.1056176/) and on Discord. This will help us keep track of how many users are interested in this.
(Please upvote this issue or leave a comment if you are interested in this)

**Is your feature request related to a problem? Please describe.**
Having a separate project for the server and client is a commonly used pattern when developing multiplayer games. Right now this might be possible in MLAPI but it's hard to achieve and we lack documentation about how to do it. 

**Describe the solution you would like:**
Documentation or a sample showing how to use MLAPI with a separate server and client project.

**Comment by DasOhmoff** [comment]
Yes! Please work on this, it would be very helpful!

**Comment by AdamBebko** [comment]
Just some brief documentation on how to separate out a server (for external hosting, or a dedicated machine) would be very helpful. Your forum post was the first time I even found out this was possible with this package. I'm currently using Dots Netcode, which is painful, to say the least. It would be great to switch back to game objects.

**Comment by Briancoughlin** [comment]
THis is now going to be added to the backlog as an item to be done thanks for all you voting and comments

**Comment by DiegoSynth** [comment]
Yes please, documentation and / or tutorial would be great.
Separated client from server is the only way of keeping things nice and tidy with a good design.
Please update us on this!

**Comment by Fiona** [comment]
+1 Am looking for authoritive solutions to this in the docs.

**Comment by ThatGhost** [comment]
please implement this. This would be so usefull

**Comment by PyrateAkananto** [comment]
When building MMOs we prefer to put game client and game server into different projects with some shared code in between because both projects have different requirements and because mixing everything together might get messy.

**Comment by billgan1024** [comment]
This would be a useful feature

**Comment by Celant** [comment]
This was marked as completed but I can't see any new documentation on it. Am I just missing it? 🙂
