### ISSUE TITLE
Feedback for /versioned_docs/version-0.1.0/tutorials/goldenpath_series/goldenpath_foundation_module.md

### ISSUE THREAD

**Issue by jmankinUnity** [Unity-Technologies/com.unity.multiplayer.docs#224]
The "Install MLAPI" link is broken - sends you to:

https://mp-docs.dlt.it.unity3d.com/docs/tutorials/migration/installation.md

The "Hello World" tutorial sends you to this link, which seems to be correct:

https://mp-docs.dlt.it.unity3d.com/docs/migration/install

**Comment by Briancoughlin** [comment]
not issue on production is on internal WIP build  closing as not on live
