### ISSUE TITLE
Feedback for /versioned_docs/version-0.1.0/mlapi-api/MLAPI.Messaging.CustomMessagingManager.md

### ISSUE THREAD

**Issue by Karstenx1971** [Unity-Technologies/com.unity.multiplayer.docs#236]
What exactly is a "NetworkManager Custom Message" and how to use them? If they are the ServerRpc and ClientRpc, please make this clear.

**Comment by Briancoughlin** [comment]
@Karstenx1971  does this help? https://docs-multiplayer.unity3d.com/docs/advanced-topics/message-system/custom-messages.

**Comment by s-omeilia-unity** [comment]
No response from user about issue after reply since 7/19. Assuming concern answered. Closing.
