### ISSUE TITLE
Add Linux support reference

### ISSUE THREAD

**Issue by JesseOlmer** [Unity-Technologies/com.unity.multiplayer.docs#237]
Linux is a supported target. Right now our automation runs against Ubuntu, but before release we also will be looking at supporting centos

We are targeting support for the same platforms Unity does, no more, no less - that is: Ubuntu 20.4 LTS, Ubuntu 18.04 LTS, CentOS 7. https://forum.unity.com/threads/unity-2020-2-unity-linux-distro-support.970059/

**Comment by Briancoughlin** [comment]
MTTDOC-290 linked Jira ticket
