### ISSUE TITLE
Feedback for /versioned_docs/version-0.1.0/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by JRussas** [Unity-Technologies/com.unity.multiplayer.docs#244]
The directions tell someone to "Clone" their project directory by creating a copy, but when I followed these steps my new project binaries were not being generated in the new directory structure we just created.  I had to go in and select the new build location in my new GoldenPath_One project.

I don't know if it's just me but the timestamp on the binaries created when building don't have an accurate timestamp.  They appear to probably be when unity was installed on this machine.  This makes it harder to realize the binaries aren't being updated with each build.  I had to delete them and build to realize they weren't being generated.

Perhaps at a later date cloning the directory will make sense but for tutorials that build on one another we're just creating another directory that takes up space.  Until a tutorial has a user make code changes that would be conflicting and project breaking there isn't much value in cloning the previous lesson.  The user should just be using the same project.

**Comment by Briancoughlin** [comment]
@JRussas, The aim was to cut down on repeating steps as much as possible. I think I will rework the section to call that out more and leave it as a user choice to clone or not clone, your thoughts?

**Comment by JRussas** [comment]
When I started on GoldenPath_Two I simply kept using my GoldenPath_One project.  Is there a reason you feel that they would need to have a new project versus just using the same one?  Like I said if there are future tutorials that will cause conflicts with each other I can see splitting them.

The build output issue seems like the bigger deal to me as it took me a little bit to track down why my changes weren't showing up.  Because I type out the code instead of just copying and pasting it I had to verify I hadn't made a mistake.

**Comment by Briancoughlin** [comment]
@JRussas  there is going to be more golden paths in the future and I was trying to save users effort.  Most if not all of our golden paths start with the  same steps, which i was worried would bore users.  From what your saying that might have been the wrong path.

**Comment by JRussas** [comment]
Your logic makes complete sense.  Personally I tend to make prefabs that I reuse and then drop in to future projects.  That may be a good solution here?    

Honestly having followed the steps you've put a lot of thought into what a user is trying to do and it's easy to follow your steps.  Everything is well written.  The only thing that caught me up was my output still going to my old directory.

Thank you for the quick response on this "issue" and great job on these.  They are appreciated!
