### ISSUE TITLE
Error in the documentation (Object Pooling)

### ISSUE THREAD

**Issue by LuckSmile** [Unity-Technologies/com.unity.multiplayer.docs#245]
**Error in the documentation**

![image](https://user-images.githubusercontent.com/73651390/127568230-745c15ce-0c79-43f8-ad73-e69920932b0b.png)
![image](https://user-images.githubusercontent.com/73651390/127568268-86a59c64-58fb-4d53-88c0-07bf191c7f5d.png)

**Comment by s-omeilia-unity** [comment]
Captured in updates to this doc in the `develop` version of documentation.
