### ISSUE TITLE
Feedback for /transport_versioned_docs/version-0.8.0/samples/jobifiedserverbehaviour.cs.md

### ISSUE THREAD

**Issue by Sneirox** [Unity-Technologies/com.unity.multiplayer.docs#249]
The current code do not support a new transport API

**Comment by Sneirox** [comment]
- ServerJobHandle = serverUpdateJob.Schedule(...) - incorrect params.
- struct ServerUpdateJob : IJobParallelForDefer - (maybe IJobParallelFor ?)

**Comment by Briancoughlin** [comment]
This is now added to our backlog. Thanks for your contribution
