### ISSUE TITLE
Broken nativelist link in server behaviour guide

### ISSUE THREAD

**Issue by JesseOlmer** [Unity-Technologies/com.unity.multiplayer.docs#252]
The link to Native List in this section of the page is broken.
`You need to declare a NetworkDriver. You also need to create a NativeList to hold our connections.`

**Comment by JesseOlmer** [comment]
/transport_versioned_docs/version-0.8.0/workflow-client-server.md

**Comment by chrispope** [comment]
PR submitted - awaiting review.
