### ISSUE TITLE
Feedback for /versioned_docs/version-0.1.0/getting-started/about-mlapi.md

### ISSUE THREAD

**Issue by manfredhq** [Unity-Technologies/com.unity.multiplayer.docs#274]
Some links doesn't work properly when left clicking on it.
The two links I have noticed so far are those under "Hello World".
![image](https://user-images.githubusercontent.com/38951963/131263553-20155d63-0cc9-489d-b37c-23828bd5e3db.png)
But wheel cliking or right click open works great.

Here is a gif of the issue.
![Alt Text](https://i.gyazo.com/d55dc73bb3cf93e6ad775e388e406d1a.gif)

**Comment by Briancoughlin** [comment]
@manfredhq  it seems to be working now ( i could see your issue last night, ill do some more testing can you confirm if you can still see the issue your end please)

**Comment by manfredhq** [comment]
The hyperlinks works without any issue now.
Thanks for your time.
