### ISSUE TITLE
Feedback for /versioned_docs/version-0.1.0/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by robin-demoor** [Unity-Technologies/com.unity.multiplayer.docs#275]
The "Testing the command line helper" links in the guide don't seem to work for me (happened on two devices both chrome browser on a desktop)

**Comment by s-omeilia-unity** [comment]
Looking into this now. 

I see that the links seem to do nothing for me and opening in a new tab just leads to the top of the doc. Looking for the cause.

**Comment by s-omeilia-unity** [comment]
Cause: Links are pointing to a header that doesn't exist on that page but exists on the "GoldenPath Foundation Module".

Making updates now.
