### ISSUE TITLE
Documentation implies NamedMessages will send from Host to Local Client, but they do not. 

### ISSUE THREAD

**Issue by GorillaOne** [Unity-Technologies/com.unity.multiplayer.docs#28]
**Describe the bug**
Not sure if a bug or intended, but the documentation heavily implies (both by proximity of Named Message documentation to RPC documentation, where RPC's are called on the hosts local client) that named messages can be sent from the host to the local client. This is not the case. 

**To Reproduce**
1. Register a named message handler on the host. 
2. Send a custom named message from the host to the local client id. 
3. Message is not sent or received. 

**Expected behavior**
Based on the documentation I would expect this message to be received by the client via an internal message. 

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Unity Version: 2020.1.14f1
 - MLAPI Version: v12.1.7
 - MLAPI Commit: Latest. 

**Additional context**
Without being able to send named messages locally, it will require two message pipelines from a host controller - one for remote clients, and one for the local client.

**Comment by Briancoughlin** [comment]
@LukeStampfli  is this still an issue with the updated docs.

**Comment by LukeStampfli** [comment]
This is still an issue as in we don't document it so it's not clear that's not supported.

**Comment by Briancoughlin** [comment]
So we need to update the docs to clarify that its not supported  Will do a PR for that

**Comment by Briancoughlin** [comment]
this is now on the backlog to be done thanks for your contribution

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
