### ISSUE TITLE
Jsiho

### ISSUE THREAD

**Issue by jaiho123** [Unity-Technologies/com.unity.multiplayer.docs#291]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.

**Steps to reproduce the behavior:**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior:**
Describe what you expected to happen.

**Screenshots**

**Desktop/Tablet/Smartphone (please complete the following information):**

**Additional info:**

**Comment by s-omeilia-unity** [comment]
@jaiho123 What is the bug or issue you are experiencing?

**Comment by Briancoughlin** [comment]
Closing as not sure it was a genuine issue
