### ISSUE TITLE
Feedback for /versioned_docs/version-0.1.0/migration/installation.md

### ISSUE THREAD

**Issue by TheInventorist** [Unity-Technologies/com.unity.multiplayer.docs#303]
I was basically following the tutorial and when I needed to copy the git line it didn't work showing this error message.

[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi.git?path=/com.unity.multiplayer.mlapi#release/0.1.0]:
  Error when executing git command. fatal: invalid branch name: init.defaultBranch = 
 [NotFound].
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

**Comment by Briancoughlin** [comment]
@TheInventorist are you using the copy function on the doc page or trying to select and copy. We have seen some issues when not using the Code copy function of the doc page itself. I have just tested via the copy function and its installing can you try that and see if it works for you

**Comment by TheInventorist** [comment]
I was using the copy function and didn't work. I downloaded the .zip file and imported it on unity to make it work as a workaround option. I'll check again this afternoon. Thanks for answering.

**Comment by Briancoughlin** [comment]
@TheInventorist  I have just tested the installation links for the 0.1.0 installation and it seems it work fine for me.

This is the link I copied from the documentation

https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi.git?path=/com.unity.multiplayer.mlapi#release/0.1.0

Video Link attached
https://youtu.be/Y5K3F9LvDMs

**Comment by TheInventorist** [comment]
Weird, but it's okay, maybe it was my Unity, the thing is that now it works for you and if someone else can't make it work, downloading and doing it manually also works :D! Thanks for the amazing work.
