### ISSUE TITLE
Transport sidebar: dead "Source Project for Workflows" link

### ISSUE THREAD

**Issue by simon-lemay-unity** [Unity-Technologies/com.unity.multiplayer.docs#363]
The transport's documentation sidebar contains a link titled "Source Project for Workflows" (under the "Samples" category). This link is dead and points to a non-existing resource on ownCloud.

Bug reported by a user on our forums [here](https://forum.unity.com/threads/unity-transport-source-code.1187599/).

**Comment by s-omeilia-unity** [comment]
@simon-lemay-unity Was the PR mentioned above submitted, and can I close this issue?

**Comment by simon-lemay-unity** [comment]
No, and yes. I have not yet submitted that PR. But the link will be gone soon since we'll basically be replacing our package docs with a stub that points to the multiplayer docs. This is tracked in JIRA as a task for the current sprint, so should be fine to close this issue.

**Comment by s-omeilia-unity** [comment]
Perfect. Thank you.
