### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/getting-started/maxnumberplayers.md

### ISSUE THREAD

**Issue by Fincap** [Unity-Technologies/com.unity.multiplayer.docs#371]
First paragraph, link to "connection approval delegate" (url: https://docs-multiplayer.unity3d.com/docs/mlapi-api/MLAPI.NetworkManager.ConnectionApprovedDelegate.md) leads to a Page Not Found.

**Comment by Briancoughlin** [comment]
this is now fixed under Feedback for /versioned_docs/version-1.0.0/getting-started/maxnumberplayers.md #377
