### ISSUE TITLE
Feedback for /docs/tutorials/goldenpath_series/goldenpath_foundation_module.md

### ISSUE THREAD

**Issue by manuelfalonso** [Unity-Technologies/com.unity.multiplayer.docs#373]
Hi, there is a small error that you can check in:
Testing the command line helper
-> IMPORTANT section
-> Example (Running as a single command line):
-> C:\Users\sarao>GoldenPath\Build\GoldenPath.exe -logfile -log-server.txt -mlapi server & GoldenPath\Build\GoldenPath.exe -logfile log-client.txt -mlapi client

**"-log-server.txt" should not be with a initial hyphen**

In the NetworkCommandLine script you are ignoring (setting null) the second value if starts with hyphen.

            if (arg.StartsWith("-"))
            {
                var value = i < args.Length - 1 ? args[i + 1].ToLower() : null;
                value = (value?.StartsWith("-") ?? false) ? null : value;

                argDictionary.Add(arg, value);
            }

**Comment by s-omeilia-unity** [comment]
Duplicated issue.
#416
