### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/basics/networkvariable.md

### ISSUE THREAD

**Issue by pulsartronic** [Unity-Technologies/com.unity.multiplayer.docs#376]
It seems that NetworkVariableSettings class is not part of my environment,, it is in the docs yet VisualStudio can't find it, therefore it's not possible to make this line compile

`private NetworkVariable<float> myFloat = new NetworkVariable<float>(new NetworkVariableSettings {WritePermission = NetworkVariablePermission.OwnerOnly}, 5);`

... which is indicated here https://docs-multiplayer.unity3d.com/docs/basics/networkvariable

Here's my environment
Unity 2020.3.4

Image from Unity's docs
![image](https://user-images.githubusercontent.com/59339572/139512637-3007104d-e597-4d4a-adb0-060cd6f1c6f1.png)

Image from my project
![image](https://user-images.githubusercontent.com/59339572/139512673-a3400d7b-aca9-4f2d-92c0-0ef35022e0c2.png)

**Comment by s-omeilia-unity** [comment]
This entire doc has been updated and reviewed by dev. Content is up-to-date 3/30/22.
