### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/advanced-topics/message-system/custom-messages.md

### ISSUE THREAD

**Issue by tdautreme** [Unity-Technologies/com.unity.multiplayer.docs#391]
How to use this ?
In the example you use the class method like they are static but they are not.
Then how to use the methods ? Instantiate the CustomMessagingManager ? Can't because no constructor...

**Comment by aryansaurav** [comment]
I had the same question! Any update @s-omeilia-unity . 

Would be greatly appreciated. thanks!

**Comment by s-omeilia-unity** [comment]
Addressed with PR #673, pushing to live now
