### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/getting-started/about.md

### ISSUE THREAD

**Issue by Jalict** [Unity-Technologies/com.unity.multiplayer.docs#396]
The link to "Your First Networked Game" under "Hello World" does work not correctly. When I click the link it proceeds to 
`https://docs-multiplayer.unity3d.com/docs/tutorials/helloworld/helloworldintro`

But if I open it in a new tab it seems to be redirected to 
`https://docs-multiplayer.unity3d.com/docs/tutorials/helloworld/helloworldintro/index.html` 

Seems like the redirect does not work probably?

Using Firefox 94.0.1 (64-bit)

**Comment by s-omeilia-unity** [comment]
Link fixes went in to hopefully address this problem among other link changes. These links work at this time.
