### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/tutorials/helloworld/helloworldintro.md

### ISSUE THREAD

**Issue by joaovtor64** [Unity-Technologies/com.unity.multiplayer.docs#400]
"Now we will test to see if evereything works as expected."
Everything is spelled wrong

I'm new to github so sorry if i did something wrong here

**Comment by Briancoughlin** [comment]
@joaovtor64  should now be fixed on live. you did it perfectly so no worries good spot thanks.
