### ISSUE TITLE
Outdated docs /versioned_docs/version-1.0.0/basics/networkvariable.md

### ISSUE THREAD

**Issue by a-coox** [Unity-Technologies/com.unity.multiplayer.docs#411]
The permissions section of the `NetworkVariable` documentation is outdated and contains a code snippet that uses `NetworkVariableSettings`:

```
private NetworkVariable<float> myFloat = new NetworkVariable<float>(new NetworkVariableSettings {WritePermission = NetworkVariablePermission.OwnerOnly}, 5);
```

**Comment by s-omeilia-unity** [comment]
This entire doc has been updated and reviewed by dev. Content is up-to-date 3/30/22.
