### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/tutorials/goldenpath_series/goldenpath_foundation_module.md

### ISSUE THREAD

**Issue by MScottAdams** [Unity-Technologies/com.unity.multiplayer.docs#417]
Windows Batch file recommendations for starting client and server or both

Put the following single line batch files in the build directory. Then from Windows explorer double click on the one needed and it will execute and also set the log file to be written in the build directory. 
This also fixes a problem where the original code example would not start both client and server but wait for one to complete before starting the next one.

RunClient.bat
`GoldenPath.exe -mlapi client -logfile log-client.txt `

RunServer.bat
`GoldenPath.exe -mlapi server -logfile log-server.txt `

RunBoth.bat
`start GoldenPath.exe -mlapi server -logfile log-server.txt & GoldenPath.exe -mlapi client -logfile log-client.txt`

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
