### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by AstralStew** [Unity-Technologies/com.unity.multiplayer.docs#424]
The code snippet for the "Introducing a Server-controlled Network Variable" step only includes the server code. It is missing the client code shown in the video during the next step (e.g. ClientNetworkVariable, etc)

**Comment by AstralStew** [comment]
I see the video has an older version of the code. I suppose a more accurate description of my issue would be that the current example no longer logs the network variable in the client log file. I think it would be clearer what was going on if it was written like this or something:

`if (IsServer) {
            ServerNetworkVariable.Value = ServerNetworkVariable.Value + 0.1f;
        }

        var t_now = Time.time;
        if (t_now - last_t > 0.5f) {
            last_t = t_now;
            Debug.Log("["+(IsServer?"Server":"Client")+"] Obj(" + gameObject.name + ") var = " + ServerNetworkVariable.Value);
        }`

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
