### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by Xander23333** [Unity-Technologies/com.unity.multiplayer.docs#428]
1. the component "NetworkVariableTest" can not output "Server set its var to: 6.099997, has client var at: 5.599997", because it has no code about "client".
2. the component "RpcTest" will loop forever if you test it in Unity Editor "Start Host" button. it should end after several loops, such as below. 
```void TestServerRpc(int value)
    {
        Debug.Log("Server Received the RPC #" + value);
        if (value > 10) return;
        TestClientRpc(value);
    }
```

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
