### ISSUE TITLE
NetCode for GameObjects v1.0.0 disconnection

### ISSUE THREAD

**Issue by GNPhoque** [Unity-Technologies/com.unity.multiplayer.docs#429]
https://docs-multiplayer.unity3d.com/docs/components/networkmanager

This page states to use NetworkManager.Singleton.StopClient() /Server/host to disconnect players but these methods are not available

**Comment by Yuzaki76** [comment]
Hi, From now on we have to use `NetworkManager.Singleton.Shutdown()` [Like to issue](https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/pull/1108)

**Comment by s-omeilia-unity** [comment]
Addressed with PR #635 that is publishing to live now
