### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/basics/networkvariable.md

### ISSUE THREAD

**Issue by HolgerDurach** [Unity-Technologies/com.unity.multiplayer.docs#432]
"boss room examples" at the bottom link is dead
https://docs-multiplayer.unity3d.com/learn/bossroom-examples/bossroom-actions

**Comment by s-omeilia-unity** [comment]
This entire doc has been updated and reviewed by dev. Content is up-to-date 3/30/22.
