### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/tutorials/testing/techniques_and_tricks_for_debugging_multiplayer_games.md

### ISSUE THREAD

**Issue by manuelfalonso** [Unity-Technologies/com.unity.multiplayer.docs#436]
Hi!! The code snippet on this page have 3 errors:

1. "using UnityEngine;" missing
2. Line 4 is a Vector3[] instead of Vector3
3. Line 19 is Vector3.up instead of Vector3.UP

before
![image](https://user-images.githubusercontent.com/52722318/145619166-1fcc5775-a25e-48c2-afc1-9c334cda7ff4.png)

after
![image](https://user-images.githubusercontent.com/52722318/145619378-80993db2-4e7b-4463-b710-82c404e95c2d.png)

**Comment by manuelfalonso** [comment]
Also all the color coding is incorrect. It's all in light blue

**Comment by s-omeilia-unity** [comment]
Addressed with updates pushing to live with PR #677
