### ISSUE TITLE
Feedback for /docs/advanced-topics/message-system/custom-messages.md

### ISSUE THREAD

**Issue by aryansaurav** [Unity-Technologies/com.unity.multiplayer.docs#437]
Hello,

The CustomMessagingManager class has not been declared as static class. Thus, when using the class methods for sending/receiving custom messages as described in the tutorial leads to NullExceptionError. Is there something that I am missing?
Or, how can we use the API for custom messaging ? Couldn't find a constructor of the class neither to instantiate an object!

**Comment by s-omeilia-unity** [comment]
Addressed with PR #673, pushing to live now
