### ISSUE TITLE
[Feedback] No mention of performance impact of Reliable RPCs in Doc (message-system/reliabilty.md)

### ISSUE THREAD

**Issue by gabrieldechichi** [Unity-Technologies/com.unity.multiplayer.docs#438]
_*This can be considered a minor suggestion, but I wanted to raise it regardless._

In [the current doc for RPC Reliability](https://docs-multiplayer.unity3d.com/docs/advanced-topics/message-system/reliability/index.html), there is no mention of the performance impact of having most RPCs as reliable. Since reliable RPCs guarantee ordered delivery, in bad network conditions (high latency, high package drop and/or too many requests), reliable RPCs will continually be re-sent, cluttering the network and possibly making the game unplayable.

I totally agree that RPCs should be reliable by default, since it makes things easier, and that this is a intro doc, but I think it would be helpful to mention that, at least for fast paced multiplayer games, unreliable RPCs might be the most common case, rather than the exception, even for some non-cosmetic gameplay actions (as long as those are non critical).

Also, I think raising awareness of the impact of reliable messages is generally useful for someone looking to build a multiplayer game.

**Comment by Briancoughlin** [comment]
@LukeStampfli  is this something we can add to the doc  in the upcoming doc pass or is it something that needs a page of its own

**Comment by s-omeilia-unity** [comment]
Addressed with PR #671, pushing live now.
