### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/migration/installation.md

### ISSUE THREAD

**Issue by pajama** [Unity-Technologies/com.unity.multiplayer.docs#439]
2020.3 instructions require a git url but only shows the package name

**Comment by Briancoughlin** [comment]
this is an odd one. Unity 2020.3 has the package name option included in the git url selection. so it works if you only enter a Name but the UI doesn't show that option. I will try and find a way to update the page text to better reflect this oddity

**Comment by Briancoughlin** [comment]
closed with #478
