### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/tutorials/goldenpath_series/starting-out.md

### ISSUE THREAD

**Issue by HonorsoftEntertainment** [Unity-Technologies/com.unity.multiplayer.docs#443]
The buttons for "Golden Path Foundation Module", "Golden Path Module One" and "Golden Path Module Two" are broken.
The buttons all lead to a "404 not found" page.

Here are the links:

https://docs-multiplayer.unity3d.com/docs/tutorials/goldenpath_series/goldenpath_foundation_module
"Golden Path Foundation Module"
Creating a new project
Installing Netcode
Creating and testing the basic networking building blocks

https://docs-multiplayer.unity3d.com/docs/tutorials/goldenpath_series/goldenpath_one
"Golden Path Module One"
Adding scripts to objects
Editor modes (Host Server and Client)
Basic player movement
Basic RPC use

https://docs-multiplayer.unity3d.com/docs/tutorials/goldenpath_series/goldenpath_two
"Golden Path Module Two"
Network variables (client and server-controlled)
Network transforms
More on RPCs

**Comment by Briancoughlin** [comment]
Closing as not seeing the issue on production at moment

**Comment by HonorsoftEntertainment** [comment]
Sorry for the late response, the links do appear to be working (it was not an internet issue on my end before). *I believe that the links were posted in the help documentation, but lead to a 404 page before but seem to be working now, so disregard this issue. It could have just been an link-error on the documentation page that has been fixed.
