### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/basics/networkvariable.md

### ISSUE THREAD

**Issue by OndrejPetrzilka** [Unity-Technologies/com.unity.multiplayer.docs#445]
Explain when OnValueChanged is called exactly.
There's currently only "when value is changed".

What does it mean?

When it's changed by other peer/server in network?
When it's changed locally?
What about initial values that comes when spawning object over network, is it invoked as well or not?

**Comment by s-omeilia-unity** [comment]
Addressed by PR #661 going live now
