### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by samhubbard** [Unity-Technologies/com.unity.multiplayer.docs#447]
The NetworkVariableTest.cs shown in the tutorial is different from the one that is being used in the YouTube video. There is no ClientNetworkVariable in the provided NetworkVariableTest.cs. And, from what I can tell, the client isn't allowed to change the value of a network variable.

So, it appears that this section just needs to be cleaned up.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
