### ISSUE TITLE
Feedback for /docs/components/networkmanager.md

### ISSUE THREAD

**Issue by repus-trams** [Unity-Technologies/com.unity.multiplayer.docs#448]
NetworkManager.Singleton.StopHost();
NetworkManager.Singleton.StopClient();
and
NetworkManager.Singleton.StopServer();
have all been removed from Unity.Netcode.

**Comment by repus-trams** [comment]
`public void Disconnect()
{
    NetworkManager.Singleton.Shutdown();
    
    UnityEngine.SceneManagement.SceneManager.LoadScene("MainMenu");
}`

Possible change to the docs

**Comment by s-omeilia-unity** [comment]
Addressed with PR https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/635 that is publishing to live now
