### ISSUE TITLE
Golden Path Module One - HelloWorldPlayer position raises compilation warning

### ISSUE THREAD

**Issue by YajJackson** [Unity-Technologies/com.unity.multiplayer.docs#449]
**Provide Feedback on Docs**
`HelloWorldPlayer.position` raises compilation warning:
```csharp
public NetworkVariable<Vector3> Position = new NetworkVariable<Vector3>();
/*
The type 'UnityEngine.Vector3' cannot be used as type parameter 'T' in the generic type or method 'NetworkVariable<T>'.
There is no boxing conversion from 'UnityEngine.Vector3' to 'unmanaged'. [Assembly-CSharp]
*/
``` 

**Specific page:**
[GoldenPath Module One - HelloWorldPlayer](https://docs-multiplayer.unity3d.com/docs/tutorials/goldenpath_series/goldenpath_one#adding-basic-movement-to-the-player-object)

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
