### ISSUE TITLE
Edit this page button is broken

### ISSUE THREAD

**Issue by LukeStampfli** [Unity-Technologies/com.unity.multiplayer.docs#456]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.

**Steps to reproduce the behavior:**
1. Go to any docs page
2. Press the `edit this page` button on the top right
3. You get an 404

**Expected behavior:**
Link should work

**Additional info:**
Fairly sure the problem is that the link points to `master` instead of `main` and that's causing the issue since we renamed it. E.g ```https://github.com/Unity-Technologies/com.unity.multiplayer.docs/edit/master/versioned_docs/version-1.0.0/advanced-topics/messaging-system.md```
should be 
```https://github.com/Unity-Technologies/com.unity.multiplayer.docs/edit/main/versioned_docs/version-1.0.0/advanced-topics/messaging-system.md```

**Comment by Briancoughlin** [comment]
should now be fixed
