### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/advanced-topics/message-system/serverrpc.md

### ISSUE THREAD

**Issue by Wallace92** [Unity-Technologies/com.unity.multiplayer.docs#457]
Missing an information about important option [ServerRpc(RequireOwnership = false)]. It allows to change an NetworkVariable by the Client even it don't have an Ownership over the NetworkObject. This should be correlated with an https://docs-multiplayer.unity3d.com/docs/basics/networkvariable becasue there is an obsolete information:

"By default NetworkVariable and its subclasses can only be written to by the server (NetworkVariablePermission.ServerOnly). To change that set the permission to the desired value during initialization:
private NetworkVariable<float> myFloat = new NetworkVariable<float>(new NetworkVariableSettings {WritePermission = NetworkVariablePermission.OwnerOnly}, 5);"

No, you can't do that WritePermissions have been removed in the 1.0.0 version. You can write to NetvorkVariable onlby by RPC.

**Comment by s-omeilia-unity** [comment]
Addressed with PR #661, pushing live now.
