### ISSUE TITLE
Deprecated methods in NetworkManager's "Disconnecting" script sample

### ISSUE THREAD

**Issue by juliuspipikasunity** [Unity-Technologies/com.unity.multiplayer.docs#461]
Outdated documentation for the “Disconnecting” section. Still makes use of `StopHost()`, `StopClient()`, and `StopServer()`, all of which have been deprecated. Should probably be replaced with `Shutdown()`?

https://docs-multiplayer.unity3d.com/docs/develop/components/networkmanager/#disconnecting

**Comment by s-omeilia-unity** [comment]
Addressed with PR https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/635 that is publishing to live now
