### ISSUE TITLE
Clients can't find Their Own PlayerObject. \\\\\\\\ Feedback for /versioned_docs/version-1.0.0/basics/networkobject.md

### ISSUE THREAD

**Issue by 22tooty2** [Unity-Technologies/com.unity.multiplayer.docs#462]
#Finding Player Objects

To find a player object for a specific client id you can use the following:

NetworkManager.Singleton.ConnectedClients[clientId].PlayerObject;
To find your own player object just pass NetworkManager.Singleton.LocalClientId as the clientId in the sample above.

what if i wanted to find the local Client's player object? ConnectedClients can only be accessed by the server/host. so the clients who use this can't find their own object.

**Comment by Briancoughlin** [comment]
@LukeStampfli can you provide guidance on this?

**Comment by LukeStampfli** [comment]
```cs
var player = NetworkManager.Singleton.LocalClient.PlayerObject;
```
Can be used as a client to access the own player object.

**Comment by 22tooty2** [comment]
this part at the documentation was a little confusing. this works. thank you so much!

this can also be saved as a NetworkObject by the way.
