### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/migration/installation.md

### ISSUE THREAD

**Issue by sebastienandary** [Unity-Technologies/com.unity.multiplayer.docs#463]
In the "Unity version 2020" section the same package name `com.unity.netcode.gameobjects` is presented instead of an URL.

**Comment by Briancoughlin** [comment]
@sebastienandary 
The **Add pack from name..** option is integrated with the **Add package from git URL...** in Unity 2020.3.x versions. I am going to update the page to make this clearer thanks for the spot.
