### ISSUE TITLE
Feedback for /versioned_docs/version-0.1.0/api/MLAPI.NetworkManager.md

### ISSUE THREAD

**Issue by juliuspipikasunity** [Unity-Technologies/com.unity.multiplayer.docs#465]
The site for Multiplayer Networking documentation has some issues (not the documentation, itself!)

Some pages are missing when you try to access them from the Search window. For example:
https://docs-multiplayer.unity3d.com/releases/multiplayer/release-1.0.0/index.html#removed (found by searching for “stopserver()”)

Other times, the version of the package is changed from develop to 0.1.0 or 1.0.0, when trying to access some pages from the Search window. For example:
https://docs-multiplayer.unity3d.com/docs/0.1.0/api/MLAPI.NetworkManager/index.html#stopclient (found by opening the search dialogue and searching for StopClient, while “develop” version is selected)

**Comment by Briancoughlin** [comment]
@juliuspipikasunity 

So the first one im going to investigate it looks like an issue with the indexing for search.......

The second one the version might be changing as it is not a version filtered search. The Multiplayer search works across all version ( unlike the main unity site) so it will find entries for all versions. That particular link is for the 0.1.0 version as shown in the URL. so it will go there and change the version to reflect the page info.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
