### ISSUE TITLE
Feedback for /versioned_docs/version-1.0.0/tutorials/helloworld/helloworldintro.md

### ISSUE THREAD

**Issue by maxg0** [Unity-Technologies/com.unity.multiplayer.docs#467]
~Player prefab creation is now done by dragging the prefab to the player prefab field, not by adding it to network prefabs.~

Actually this is reflected the latest documentation, where the Player Prefab slot is mentioned ("Drag the prefab also into the Player Prefab slot."), but it seems to work even when not added separately to network objects. Should the player prefab also be added to network prefabs?

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
