### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/basics/object-spawning.md

### ISSUE THREAD

**Issue by scott-lin** [Unity-Technologies/com.unity.multiplayer.docs#481]
Documentation doesn't match code... https://docs-multiplayer.unity3d.com/docs/basics/object-spawning#spawning-a-networked-prefab

```
The .Spawn() method takes 2 optional parameters, both with default values:

public void Spawn(Stream spawnPayload = null, bool destroyWithScene = false);
```

Code at https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/blob/427e36ce571e32164850cf6c81bd97ebaa4d6bd2/com.unity.netcode.gameobjects/Runtime/Core/NetworkObject.cs#L471 and pasted below for convenience.

```
public void Spawn(bool destroyWithScene = false)
```

Am I missing something?

**Comment by s-omeilia-unity** [comment]
Updated with this PR: https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/636
Building to live now
