### ISSUE TITLE
Dead link on gp_module_two.md

### ISSUE THREAD

**Issue by klilley** [Unity-Technologies/com.unity.multiplayer.docs#489]
Launch the client and server together in a terminal as shown in "Testing the command line helper."

https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/main/versioned_docs/version-1.0.0/tutorials/goldenpath_series/gp_module_two.md#testing-the-command-line-helper

That link doesn't exist, the tutorial is not informing on how to output to the console.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
