### ISSUE TITLE
Feedback for ersioned_docs/version-0.1.0/tutorials/helloworld/helloworldparttwo.md

### ISSUE THREAD

**Issue by jorisatabix** [Unity-Technologies/com.unity.multiplayer.docs#491]
When doing example on https://docs-multiplayer.unity3d.com/docs/0.1.0/tutorials/helloworld/helloworldtwo#adding-basic-movement-to-the-player-object I am getting the following message:

<img width="496" alt="image" src="https://user-images.githubusercontent.com/36499489/151654610-764a1118-5cfb-44b6-9321-55272a833660.png">

It seems to be missing from the documentation that you should add a network object to the player prefab.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
