### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by flightCrazed** [Unity-Technologies/com.unity.multiplayer.docs#493]
Hello world was great. Golden path not so much. Hello world went over **what** and most importantly **why**. Golden part is just what to type in. There was no explanation of as to why on anything.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
