### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/components/networkanimator.md

### ISSUE THREAD

**Issue by cantaspinar** [Unity-Technologies/com.unity.multiplayer.docs#494]
NetworkAnimator seems to be server authoritative only. Ideally, we should have a client authoritative version of this component like we have with the NetworkTransform & ClientNetworkTransform. Maybe ClientNetworkAnimator? 

This would be important when migrating from other networking solutions like UNET, Mirror or Photon as they have the client authoritative options.

**Comment by s-omeilia-unity** [comment]
Addressed with PR #665 and pushing to live now
