### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/tutorials/helloworld/helloworldintro.md

### ISSUE THREAD

**Issue by MichaelMacha** [Unity-Technologies/com.unity.multiplayer.docs#495]
This tutorial presumes that a UNetTransport already exists in the scene in step seven of "Creating a Network Manager and Selecting the Transport". As someone relatively new to networking in Unity, it took me quite some time to figure out that a Network Transport is a type of component, which needed to be added to the scene first.

I know this API is still changing, but if someone could properly update that with the missing steps it would help many of us, who are trying to stay ahead of the game, out!

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
