### ISSUE TITLE
Feedback for StopHost(), StopClient(), and StopServer() deprecation

### ISSUE THREAD

**Issue by juliuspipikasunity** [Unity-Technologies/com.unity.multiplayer.docs#496]
Alternatives to StopHost(), StopClient(), and StopServer() have not been provided in the documentation after deprecation.

Perhaps the old pages for these three methods should still be available, but would note that the alternative is now ShutDown().

**Comment by s-omeilia-unity** [comment]
Addressed with PR https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/635 that is publishing to live now
