### ISSUE TITLE
NetworkAnimator won't work with client setting params missing from documentation

### ISSUE THREAD

**Issue by UnityGio** [Unity-Technologies/com.unity.multiplayer.docs#497]
> As Luke said on Discord their new implementation is Server Authoritive, i managed to get them working too, but i used Rpc's to call the values. This is a pain if you want a Client Authoritive Game....

 if this is the case can we please update the documentation (https://docs-multiplayer.unity3d.com/docs/components/networkanimator) that it won't work with clients setting params on the animator? It seems to imply that all you need to do is add a `NetworkAnimator` and you're good to go. Spent quite a few hours debugging the `NetworkAnimator` script only to find that it may actually be a bug?

Let me know if I misunderstood this. Thanks!

_Originally posted by @Shivang44 in https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/issues/1348#issuecomment-1001108576_

**Comment by LukeStampfli** [comment]
Moving this to the correct repository

**Comment by ewendel88** [comment]
It it the intention to allow network animator to be client authoritative? Or should I go ahead and add manual syncing of animator properties?

**Comment by s-omeilia-unity** [comment]
Addressed with PR #665 and pushing to live now
