### ISSUE TITLE
Feedback for ocs/components/networkmanager.md

### ISSUE THREAD

**Issue by r4gTime** [Unity-Technologies/com.unity.multiplayer.docs#498]
Methods used don't exist:
NetworkManager.Singleton.StopHost();
NetworkManager.Singleton.StopClient();
NetworkManager.Singleton.StopServer();

**Comment by SushiWaUmai** [comment]
Duplicate of #496

**Comment by s-omeilia-unity** [comment]
Addressed with PR https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/635 that is publishing to live now
