### ISSUE TITLE
error CS0103: The name 'PhotonAppSettings' does not exist in the current context

### ISSUE THREAD

**Issue by ReedySpeedy** [Unity-Technologies/com.unity.multiplayer.docs#499]
I am currently working to implement the Networking system from BossRoom into my own project so that I can learn how High-Level Networking is implemented in the new Unity Netcode for Gameobjects system.I have reached a point on the "MainMenu" scene that I'm stuck on. 
After downloading the "Photon Realtime Transport for Netcode for GameObjects" Unity package, I am receiving the error: Library/PackageCache/com.community.netcode.transport.photon-realtime@da6250d3a9/Runtime/PhotonRealtimeTransport.cs(170,50): error CS0103: The name 'PhotonAppSettings' does not exist in the current context
This error is NOT being thrown in the BossRoom project and the scripts are identical between my project and the example project. HOW can I overcome this CS0103 error?

<img width="2403" alt="Screen Shot 2022-02-08 at 4 24 19 PM" src="https://user-images.githubusercontent.com/39390202/153078119-aef31853-6fa9-4fd1-9bf3-f64e8980b078.png">

**Comment by s-omeilia-unity** [comment]
I know Photon is being removed by the 1.1.0 Boss Room release, but do you have any quick guidance on this error @Sam-Unity?

**Comment by SamuelBellomo** [comment]
Hey @ReedySpeedy if photon by itself isn't a priority for you, then you'll be interested in our latest boss room update coming out today or tomorrow. You can subscribe to our github repo here to get notified on when it comes out (and also look out for updates in our discord channel)
