### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/learn/getting-started-boss-room.md

### ISSUE THREAD

**Issue by davidc02** [Unity-Technologies/com.unity.multiplayer.docs#500]
The link for [Photon Transport for Netcode for GameObjects](https://github.com/Unity-Technologies/mlapi-community-contributions/tree/master/Transports/com.mlapi.contrib.transport.photon-realtime) is broken.

**Comment by s-omeilia-unity** [comment]
Photon is no longer supported by Boss Room and link has been removed. Will be live shortly.
