### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/getting-started/connection-approval.md

### ISSUE THREAD

**Issue by SushiWaUmai** [Unity-Technologies/com.unity.multiplayer.docs#503]
The server-side connection approval example code is outdated.

**Comment by thachhoang1909** [comment]
Hi @SushiWaUmai, do you have any document related to how to implement this on the new version? 
I try to get the prefab hash of a prefab in NetworkPrefabs but there is no functions to do that.

**Comment by SirRell** [comment]
`using Unity.Netcode;` is the only namespace you need. Instead of `MLAPI.NetworkManager.ConnectionApprovedDelegate` use just `NetworkManager.ConnectionApprovedDelegate`
