### ISSUE TITLE
Issue in ersioned_docs/version-1.0.0/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by ldevoto** [Unity-Technologies/com.unity.multiplayer.docs#508]
Hello!
I am following the golden path modules and I noticed that in the second module of the 1.0.0 documentation, the first script is incomplete.
The documentation mentions that you should see
```
Server's var initialized to: 0
Server set its var to: 0.1, has client var at: 0
Server set its var to: 3.099999, has client var at: 2.6
Server set its var to: 6.099997, has client var at: 5.599997
```
However, the given script does not print the client variable and it is not clear how to implement it.
If I look at branch develop, I see that the script references a client variable that is not defined. I don't know which version will be the final one, but it was left on both sides half way.
Thank you!

Pd: Very good tutorials 🚀

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
