### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/advanced-topics/message-system/serverrpc.md

### ISSUE THREAD

**Issue by Nelson-Christensen** [Unity-Technologies/com.unity.multiplayer.docs#513]
It should be mentioned that you can only call a ServerRPC by the NetworkObject owner per default. But it can be changed with the `[ServerRpc(RequireOwnership = false)]` flag

**Comment by s-omeilia-unity** [comment]
Addressed with PR #666, pushing live now.
