### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/advanced-topics/networkobject-parenting.md

### ISSUE THREAD

**Issue by jeffreyrainy** [Unity-Technologies/com.unity.multiplayer.docs#515]
The SDK doesn't support spawning nested NetworkObject. As such, all the parenting example and diagrams should start with non-nested Network object and then show parenting under other objects. If we want to show parenting away from a NetworkObject, it needs to be shown in steps:

- A and B not parented
- A parented under B
- A parented under something else

**Comment by s-omeilia-unity** [comment]
Addressed with this PR building to live now: https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/655
