### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/tutorials/goldenpath_series/starting-out.md

### ISSUE THREAD

**Issue by alexis-sotelo** [Unity-Technologies/com.unity.multiplayer.docs#524]
Button URLs are broken. The golden path appends to the starting-out url instead of replacing it.

Button url
https://docs-multiplayer.unity3d.com/docs/tutorials/goldenpath_series/**starting_out**/goldenpath_foundation_module
Expected url
https://docs-multiplayer.unity3d.com/docs/tutorials/goldenpath_series/goldenpath_foundation_module/index.html

**Comment by PythooonUser** [comment]
The button URLs are no longer broken. I think this issue can be closed.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
