### ISSUE TITLE
dead link to example

### ISSUE THREAD

**Issue by ThompZon** [Unity-Technologies/com.unity.multiplayer.docs#530]
Link at bottom of page has:

"
See [examples](https://docs-multiplayer.unity3d.com/learn/bossroom-examples/bossroom-actions) of how these were used in Boss Room.
"

but link leads to a 404
![image](https://user-images.githubusercontent.com/2388527/156644677-fa037cf1-798c-407c-a8cd-7c956626012f.png)

Also: section with:
"Example NetworkVariable and NetworkStart" has the following text:
"You can perform a [NetworkStart](https://docs-multiplayer.unity3d.com/docs/basics/networkbehavior) Start or Awake to subscribe the OnValueChanged of the health variable, then unsubscribe OnDestroy"

but the example uses `OnEnable` and `OnDisable`, leading to confusion to the reader.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
