### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/basics/networkvariable.md

### ISSUE THREAD

**Issue by ThompZon** [Unity-Technologies/com.unity.multiplayer.docs#532]
Missing the following section:
"
Error when connecting after imps have died: The following is a small gotcha we encountered while developing Boss Room. Using NetworkVariables is not magical. If you use OnValueChanged, you still need to make sure you initialize your values when spawning for the first time. OnValueChanged will not be called when connecting for the first time, only for the subsequent value changes.
"
from https://docs-multiplayer.unity3d.com/docs/learn/rpcnetvarexamples saved me. 

Note that this "small gotcha" is indicating that the current documentation almost lies when it say: 
`When a client connects initially to a host, all relevant NetworkVariable latest values "state" will be replicated to that new client. Your state gets updated at regular intervals.`

**Comment by s-omeilia-unity** [comment]
Addressed by PR #661 going live now
