### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/basics/networkvariable.md (syncing strings needs clarification)

### ISSUE THREAD

**Issue by powersupersport** [Unity-Technologies/com.unity.multiplayer.docs#533]
It would be nice to clarify how to synchronize strings with `NetworkVariable`. The `FixedString512Bytes` (and all 32/64/128 etc. byte families) struct exists as part of `Unity.Collections` and will probably do the job, but it's not hinted for `NetworkVariable`. I needed quite some time to figure that out.

**Comment by s-omeilia-unity** [comment]
Addressed by PR #661 going live now
