### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/advanced-topics/network-update-loop-system/index.md

### ISSUE THREAD

**Issue by ghandhikus** [Unity-Technologies/com.unity.multiplayer.docs#534]
Page does not describe how to add any kind of events to it. Please add an example.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
