### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/tutorials/goldenpath_series/goldenpath_foundation_module.md

### ISSUE THREAD

**Issue by Pokkt-SubhajitK** [Unity-Technologies/com.unity.multiplayer.docs#536]
The section where it says to add the Player object to the NetworkPrefabs, needs to be updated to adding the Player object in the PlayerPrefab field in NetworkManage component. Adding the Player object in NetworkPrefabs doesn't spawn the Player on Start Host.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
