### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/basics/networkvariable.md "NetworkVariableSettings" doesn't exist anymore

### ISSUE THREAD

**Issue by patrickdevarney** [Unity-Technologies/com.unity.multiplayer.docs#537]
The docs cite an example using "NetworkVariableSettings" to allow clients to write to NetworkVariables. I think class NetworkVariableSettings only exists in v0.1.0 and is not available anymore as of v1.0.0.

**Comment by s-omeilia-unity** [comment]
This entire doc has been updated and reviewed by dev. Content is up-to-date 3/30/22.
