### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/learn/bitesize-clientdriven.md

### ISSUE THREAD

**Issue by kroecks** [Unity-Technologies/com.unity.multiplayer.docs#539]
Documentation doesn't cover the primary topic of the article.

https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/blob/develop/com.unity.netcode.gameobjects/Samples/ClientNetworkTransform/Scripts/ClientNetworkTransform.cs

The whole point of the article is to express client authoritative movement. The only file that's relevant is this one I've linked. Without this, none of the other classes or methods matter. This has nothing to do with ClientRpc or ServerRpc or spawn points. It's all about the movement being driven by the client.

The only things that matters is this simple class that overrides the NetworkTransform to allow for client authority. Everything else is a waste of time and the article only adds confusion.

**Comment by SamuelBellomo** [comment]
Hey @kroecks thanks for the feedback, I've added a TLDR here https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/623/files#diff-985b9d4ec8a215f82ae6fb777d9b40f2caea380a8ce0d63060c46e50cf0f1954
Let me know if that makes things clearer. @s-omeilia-unity for visibility

**Comment by s-omeilia-unity** [comment]
PR #623 is building live now.
