### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/advanced-topics/message-system/serverrpc.md

### ISSUE THREAD

**Issue by alelievr** [Unity-Technologies/com.unity.multiplayer.docs#547]
Hello,

It'd be nice in the server RPC documentation to specify that the usage of `ServerRpcParams` is recommended to get the clientId of the sender instead of having the client send its clientId through the RPC params (especially since this result in a security vulnerability in the server code)

Source: https://unity.slack.com/archives/C01P4R0S2QH/p1647955428431909

**Comment by s-omeilia-unity** [comment]
Addressed with PR #666, pushing live now.
