### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by gougesa** [Unity-Technologies/com.unity.multiplayer.docs#548]
In "Introducing a Server-controlled Network Variable" the code sample is missing the parts for the Client update for NetworkVariableTest

**Comment by MaverickLoneshark** [comment]
Example's output:
```
Server's var initialized to: 0
Server set its var to: 0.1, has client var at: 0
Server set its var to: 3.099999, has client var at: 2.6
Server set its var to: 6.099997, has client var at: 5.599997
```

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
