### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/tutorials/goldenpath_series/starting-out.md

### ISSUE THREAD

**Issue by OnSightFree** [Unity-Technologies/com.unity.multiplayer.docs#550]
Hi

On this page https://docs-multiplayer.unity3d.com/docs/tutorials/goldenpath_series/starting_out

Under requirements section, the links are not working to golden path foundation and module 1 and 2.

(On the left pane ist ok though)

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
