### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/tutorials/goldenpath_series/gp_module_one.md

### ISSUE THREAD

**Issue by OnSightFree** [Unity-Technologies/com.unity.multiplayer.docs#551]
Hi

HyperLink to ServerRPC is not working properly here:
"If we are a client, we call a [ServerRpc](https://docs-multiplayer.unity3d.com/docs/advanced-topics/message-system/serverrpc.md). A ServerRpc can be invoked by a client to be executed on the server."

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
