### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/basics/networkvariable.md

### ISSUE THREAD

**Issue by RoeiRubach** [Unity-Technologies/com.unity.multiplayer.docs#552]
See [examples](https://docs-multiplayer.unity3d.com/learn/bossroom-examples/bossroom-actions) of how these were used in Boss Room.

Page Not Found

**Comment by s-omeilia-unity** [comment]
This entire doc has been updated and reviewed by dev. Content is up-to-date 3/30/22.
