### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/api/Unity.Netcode.NetworkTimeSystem.md

### ISSUE THREAD

**Issue by starchitectus** [Unity-Technologies/com.unity.multiplayer.docs#553]
"The local time is based on"
What? What is it based on? Tell me your secrets!

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
