### ISSUE TITLE
Misconception regarding the behaviour of `ref struct`s in `BufferSerializer` documentation

### ISSUE THREAD

**Issue by DaZombieKiller** [Unity-Technologies/com.unity.multiplayer.docs#554]
**Describe the bug:**
The documentation page for [`BufferSerializer`](https://docs-multiplayer.unity3d.com/docs/develop/api/Unity.Netcode.BufferSerializer-1/index.html) states the following:

> Ref structs help enforce both of those rules: they can't out live the stack context in which they were created, and they're always passed by reference no matter what.

The second part of this statement is entirely untrue. A `ref struct` is not implicitly passed by `ref`, despite the arguably confusing `ref struct` terminology. A `ref struct` will be passed by value just like a regular `struct`, it is merely capable of storing fields of `ref`-like types (such as `Span<T>`) and is thus restricted to the stack to support that.

**Expected behavior:**
The documentation should not be propagating misconceptions regarding language features.

**Screenshots**
![image](https://user-images.githubusercontent.com/6316315/160281663-82f21aac-e97b-4d39-b3bc-f8d0433cda2a.png)

**Additional info:**
I sincerely hope that this is merely a documentation error, and not a misunderstanding that has lead to an incorrect API. If code is expecting these types to be passed by `ref` implicitly, there is potentially a lot of subtly broken behaviour within the library.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.

**Comment by DaZombieKiller** [comment]
@s-omeilia-unity [The issue indeed still remains](https://docs-multiplayer.unity3d.com/netcode/current/api/Unity.Netcode.BufferSerializer-1/). I'll re-open a duplicate of this issue then.
