### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/migration/migratingfrommlapi.md

### ISSUE THREAD

**Issue by HugoJHall** [Unity-Technologies/com.unity.multiplayer.docs#558]
This appears to be out of date/broken, at least around mlapi-patcher.

**Comment by HugoJHall** [comment]
I was eventually able to get it to work, but only by downloading the patcher to a local dir, then editing the script to change name in line 211 to "com.unity.netcode.gameobjects".

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
