### ISSUE TITLE
Feedback for ocs/advanced-topics/serialization/inetworkserializable.md

### ISSUE THREAD

**Issue by AlebascoEndless** [Unity-Technologies/com.unity.multiplayer.docs#576]
Your example array serialization does not compile when used as a NetworkVariable. This should be noted probably?

error CS8377: The type 'MyCustomStruct' must be a non-nullable value type, along with all fields at any level of nesting, in order to use it as parameter 'T' in the generic type or method 'NetworkVariable<T>'

**Comment by s-omeilia-unity** [comment]
Addressed with updates pushing to live with PR #676
