### ISSUE TITLE
Use package manager instead of local clone in tutorial

### ISSUE THREAD

**Issue by Bazzagibbs** [Unity-Technologies/com.unity.multiplayer.docs#578]
In the following article:
https://docs-multiplayer.unity3d.com/netcode/current/migration/install
the tutorial says to clone the repository and add it locally. Is there a reason why it is not guiding the user to add the package in the Package Manager from the git URL?

Package Manager > + > Add package from git URL:
`https://github.com/Unity-Technologies/com.unity.netcode.gameobjects.git?path=/com.unity.netcode.gameobjects`
or more simply
`com.unity.netcode.gameobjects`

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
