### ISSUE TITLE
Transport samples missing jobs lib?

### ISSUE THREAD

**Issue by joemullenix-ks** [Unity-Technologies/com.unity.multiplayer.docs#583]
I really like these transport samples, but I've hit an issue running the 'Jobified'. Specifically, I get _"error CS0246: The type or namespace name 'IJobParallelForDefer' could not be found"_. I've been trying to install a jobs package with no success.

I'm not sure I have all of the dependencies, but the basic (non-jobified) sample runs correctly. Any ideas?

Thanks again for the clear and helpful sample code!

**Comment by s-omeilia-unity** [comment]
I'll ask the Transport devs for any clarification.

**Comment by joemullenix-ks** [comment]
Yep, that solved it. Thanks!!
