### ISSUE TITLE
Feedback for ocs/api/Unity.Netcode.FastBufferWriter.md

### ISSUE THREAD

**Issue by foxblock** [Unity-Technologies/com.unity.multiplayer.docs#594]
This page is labelled as "ByteUnpFastBufferWriteracker" in the sidebar.

![grafik](https://user-images.githubusercontent.com/816309/163713146-702cd9bd-5538-40fa-8438-3c737b0336a8.png)

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
