### ISSUE TITLE
Feedback for ocs/tools/install-tools.md

### ISSUE THREAD

**Issue by endiverse** [Unity-Technologies/com.unity.multiplayer.docs#597]
page says:

To use Netcode tools, such as the [profiler](https://docs-multiplayer.unity3d.com/netcode/current/basics/profiling), in your project, you need to install the tools package by name.

1. Open your Unity Hub and select the Project your are presently working on.
2. In the editor's menu bar, navigate to Window > Package Manager.
3. Click the plus sign (Add) in the Package Manager status bar and select Add package by name....
4. Enter com.unity.multiplayer.tools in the pop-up window and select Add.

Problem - Step 3, there is no "Add package by name" in the list.
Just Add packages from file, tarball, or git Url

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
