### ISSUE TITLE
Feedback for ocs/migration/installation.md

### ISSUE THREAD

**Issue by goudcode** [Unity-Technologies/com.unity.multiplayer.docs#606]
In the section "Next Steps" there is a link to the Golden Path page that points towards a page that does not exist:
https://docs-multiplayer.unity3d.com/netcode/current/migration/tutorials/goldenpath_series/mlapi_starting-out.md

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
