### ISSUE TITLE
Feedback for /docs/getting-started/index.md

### ISSUE THREAD

**Issue by chrispope** [Unity-Technologies/com.unity.multiplayer.docs#61]
**Provide Feedback on Docs**

Clicking the external site badge image links for release, nuget, downloads, forum and discord also enlarges the images and opens the page in a new tab. When you return to the docs site you see the badge image in focus.
![Enlarge Image issue](https://user-images.githubusercontent.com/20244654/111197898-4b175480-85bf-11eb-82d2-b20e9c4e44f0.png)

Not need to enlarge these image badges upon clicking the link.

**Comment by lkrell** [comment]
This content was removed. May add these to the readme. All images added to the site will have zoom.
