### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by faDeny** [Unity-Technologies/com.unity.multiplayer.docs#610]
Missing at "7. Edit the NetworkVariableTest.cs script to match the following.";
    private NetworkVariable<float> ClientNetworkVariable = new NetworkVariable<float>();

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
