### ISSUE TITLE
Server Behaviour Socket Bind bug

### ISSUE THREAD

**Issue by Blueduckraider50** [Unity-Technologies/com.unity.multiplayer.docs#612]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.
I tried the ServerBehaviour.cs in the samples, and I get a -1 interger when doing the m_Driver.Bind(endpoint).

I was asked on Discord to try 
`var socket = new Socket(AddressFamily.InterNetwork, SocketType.Dgram, ProtocolType.Udp);
try
 {
   socket.Bind(new IPEndPoint(IPAddress.Any, 9000));
 }
 catch(Exception e)
{
    Debug.Log("Winsock error: " + e.ToString());
}`
But it didn't give any error.
I tested to see if the port was occupied, but it wasn't, I tested ports from 7000 to 10000, all returned the same error.
Was just a blank unity 3d project, Unity 2021.3.2f1
I've tried checking if my firewall was blocking Unity or the port, they were not.
I've turned off Anti Virus, didn't help.

**Steps to reproduce the behavior:**
1. Install Unity 2021.3.2f1, Windows
2. Create new project 3D.
3. Install com.unity.transport
4. Open SampleScene (which has just Main Camera)
5. Add Gameobject, and add ServerBehaviour.cs to it (From /transport/current/samples/serverbehaviour/index.html)
6. Change `if (m_Driver.Bind(endpoint) != 0)
to
int number = m_Driver.Bind(endpoint);
Debug.Log(number);
if(number != 0)`
7. Observe -1 in the console
8. Cry because I can't find out why it doesn't want to work

**Expected behavior:**
I excepted it to not return -1, and for it to work.

![20-17-43](https://user-images.githubusercontent.com/4512636/167918738-b7031355-f3c0-4342-bfc5-16126bd4a10a.png)
![20-18-04](https://user-images.githubusercontent.com/4512636/167918775-8a498a54-db4b-4ad3-a24e-b7586d18ef4e.png)
![20-18-27](https://user-images.githubusercontent.com/4512636/167918882-a7812549-8132-494b-b518-a37731488036.png)

**Desktop/Tablet/Smartphone (please complete the following information):**
 - OS: Windows 10

**Additional info:**
sorry for any missing info

**Comment by s-omeilia-unity** [comment]
@simon-lemay-unity Is this something you are still working on?

**Comment by simon-lemay-unity** [comment]
> @simon-lemay-unity Is this something you are still working on?

I'm not actively working on it, but we're tracking it in JIRA. Feel free to close this if you wish, since it's more of a UTP issue than a documentation issue.

**Comment by s-omeilia-unity** [comment]
Thanks! Closing here.
