### ISSUE TITLE
Feedback for ocs/migration/installation.md

### ISSUE THREAD

**Issue by go2hel** [Unity-Technologies/com.unity.multiplayer.docs#615]
This is not the correct method for the installation of the netcode package. Every time cloning the repo and using that project for making multiplayer is not the solution. Update the installation procedure.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
