### ISSUE TITLE
Feedback for /docs/tutorials/helloworldparttwo.md

### ISSUE THREAD

**Issue by FredMoreau** [Unity-Technologies/com.unity.multiplayer.docs#63]
**Provide Feedback on Docs**
Steps 14 and 15 cannot be completed until steps 16 and 17 are done, as the script will otherwise not compile.
Doing steps in this order works : 13, 16, 17, 14, 15, 18.

**Comment by Briancoughlin** [comment]
Now updated thanks for the spot
