### ISSUE TITLE
Feedback for ersioned_docs/version-0.1.0/migration/installation.md

### ISSUE THREAD

**Issue by Renbo-Studio** [Unity-Technologies/com.unity.multiplayer.docs#640]
LMapi Is no more available please help

**Comment by s-omeilia-unity** [comment]
@Renbo-Studio All of documentation is going through an update over the next month, but for the most up to date docs, you'll want to make sure you are looking at the 1.0.0 version docs: https://docs-multiplayer.unity3d.com/netcode/current/migration/install

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
