### ISSUE TITLE
Feedback for ocs/advanced-topics/message-system/rpc-params.md

### ISSUE THREAD

**Issue by Lealand** [Unity-Technologies/com.unity.multiplayer.docs#641]
But what are they, though?

Neither this page nor the actual documentation page for them explain what they actually are, or how they are different than just normal function parameters.

What do they do?

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
