### ISSUE TITLE
Feedback for ocs/about.md

### ISSUE THREAD

**Issue by mikeymusch** [Unity-Technologies/com.unity.multiplayer.docs#643]
when I left click on the "Your First Networked Game" link I'm sent to a "Page not found" page, but when I middle click it, it opens https://docs-multiplayer.unity3d.com/netcode/current/tutorials/helloworld/helloworldintro/index.html in another tab which works fine

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
