### ISSUE TITLE
Feedback for ocs/tutorials/helloworld/helloworldintro.md

### ISSUE THREAD

**Issue by mikeymusch** [Unity-Technologies/com.unity.multiplayer.docs#644]
Followed this tutorial, when I got to the last step "Testing Hello World" and clicked "Play" a dialogue box popped up titled "Add Scene to Scenes in Build", the dialogue read,
"The current scene was not found in the scenes in build and a NetworkManager instance was found with scene management enabled! Clients will not be able to synchronize to this scene unless it is added to the scenes in build list.

Would you like to add it now?"
I am using unity 2021.3.5f1 which I recognize is not mentioned as supported in the docs so perhaps that's the cause.

**Comment by mikeymusch** [comment]
This also occurs in version 202.3.36f1

**Comment by 11BelowStudio** [comment]
> I am using unity 2021.3.5f1 which I recognize is not mentioned as supported in the docs so perhaps that's the cause.

Nah, it's not an issue with your Unity version. [2021.3 **is explicitly supported** by Netcode for GameObjects](https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/blob/develop/README.md).

The requirement to explicitly add the scene to the build (at least when the networkmanager has scene management enabled) just wasn't documented in the tutorial (a requirement which applies regardless of unity version)

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
