### ISSUE TITLE
Feedback for ocs/components/networkmanager.md

### ISSUE THREAD

**Issue by scott-lin** [Unity-Technologies/com.unity.multiplayer.docs#647]
The following code copied from https://docs-multiplayer.unity3d.com/netcode/current/components/networkmanager is out of date. StopHost, StopClient, and StopServer do not exist.

```
public void Disconnect()
{
    if (IsHost) 
    {
        NetworkManager.Singleton.StopHost();
    }
    else if (IsClient) 
    {
        NetworkManager.Singleton.StopClient();
    }
    else if (IsServer) 
    {
        NetworkManager.Singleton.StopServer();
    }
    
    UnityEngine.SceneManagement.SceneManager.LoadScene("MainMenu");
}
```

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
