### ISSUE TITLE
Feedback for ocs/tutorials/testing/techniques_and_tricks_for_debugging_multiplayer_games.md

### ISSUE THREAD

**Issue by vijitendrakumar** [Unity-Technologies/com.unity.multiplayer.docs#648]
I am not able connect mobile to mobile.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
