### ISSUE TITLE
Feedback for ocs/advanced-topics/object-pooling.md

### ISSUE THREAD

**Issue by DominJgon** [Unity-Technologies/com.unity.multiplayer.docs#649]
Assets/BossRoom/Scripts/Shared/Net/NetworkObjectPool.cs is not loading,
"See full example on  Github" directs nowhere (404)

![image](https://user-images.githubusercontent.com/26443656/176657933-39809ea1-f475-49ce-87c0-b80881353552.png)

**Comment by s-omeilia-unity** [comment]
PR #684 pushing to live now
