### ISSUE TITLE
Feedback for ocs/getting-started/maxnumberplayers.md

### ISSUE THREAD

**Issue by ThomH-Unity** [Unity-Technologies/com.unity.multiplayer.docs#652]
There's a reference on this page to MLAPI and the classes referenced don't seem to exist.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
