### ISSUE TITLE
Feedback for ocs/basics/networkobject.md

### ISSUE THREAD

**Issue by pkplonker** [Unity-Technologies/com.unity.multiplayer.docs#653]
When spawning a NetworkObject, the **NetowrkObject.GlobalObjectIdHash** value is used to initially identify the associatd network prefab asset clients will instantiate to create a client-local clone/copy.

Incorrect spelling of NetworkObject.

**Comment by chrispope** [comment]
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/668
