### ISSUE TITLE
Feedback for /docs/transport/install.md

### ISSUE THREAD

**Issue by LukeStampfli** [Unity-Technologies/com.unity.multiplayer.docs#66]
**Provide Feedback on Docs**
This installation guide is not working for me. If I enable preview packages in the package manager and search for `transport` or `unity transport` in the Unity registry nothing shows up. Using Unity 2020.2.0f1

**Comment by Briancoughlin** [comment]
Update install.md #89 PR created this can  be closed once the PR is merged
