### ISSUE TITLE
Feedback for ocs/learn/rpcnetvarexamples.md

### ISSUE THREAD

**Issue by julaxe** [Unity-Technologies/com.unity.multiplayer.docs#660]
The links to the github code are broken.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
