### ISSUE TITLE
project.zip does not exist in the latest release of boss room repo

### ISSUE THREAD

**Issue by hk1ll3r** [Unity-Technologies/com.unity.multiplayer.docs#669]
The setup page for boss room sample (link below) mentions clicking "project.zip" which existed in the older releases of Boss Room. The latest release however does not include that zip file.

https://docs-multiplayer.unity3d.com/netcode/current/learn/bossroom/index.html#local-multiplayer-setup

**Comment by SamuelBellomo** [comment]
woops, thanks for letting us know, fixed it
