### ISSUE TITLE
Feedback for ersioned_docs/version-0.1.0/migration/installation.md

### ISSUE THREAD

**Issue by Papayaw7** [Unity-Technologies/com.unity.multiplayer.docs#670]
The git url you gave does not exist anymore

**Comment by s-omeilia-unity** [comment]
For the most up-to-date content, you should be using the 1.0.0 documentation. MLAPI is considered defunct and replaced by Netcode for GameObjects.

https://docs-multiplayer.unity3d.com/netcode/current/installation/install
