### ISSUE TITLE
Feedback for ocs/tutorials/helloworld/helloworldintro.md

### ISSUE THREAD

**Issue by ansafon** [Unity-Technologies/com.unity.multiplayer.docs#674]
Hi,

We have a user report complaining about this tutorial being outdated.  Functions and namespaces seem to be renamed now, so you can't follow this tutorial.

Best regards,
Anastasija
Unity Customer QA Team

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
