### ISSUE TITLE
Provide better information for extrapolation

### ISSUE THREAD

**Issue by Briancoughlin** [Unity-Technologies/com.unity.multiplayer.docs#68]
In docs/reference/glossary/network-latency-management.md, the section on extrapolation is incorrect. It needs a better explanation. This is not how extrapolation actually is done.

_Originally posted by @LukeStampfli in https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/18#discussion_r591569724_

**Comment by lkrell** [comment]
Adding example to the glossary using NetworkTransform. Part of #80
