### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/starting-out.md

### ISSUE THREAD

**Issue by 11BelowStudio** [Unity-Technologies/com.unity.multiplayer.docs#680]
Looks like the goldenpath tutorial series thing hasn't been updated since Ye Olde Days of MLAPI, which probably is causing quite a bit of confusion for new users of Netcode for GameObjects (using the deprecated [`UnetTransport` in sample code](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/main/docs/shared/_create_networkmanager_and_transport.md), constant references to `mlapi` in filenames, still got a lingering reference to a ['ClientNetworkVariable' in sample code](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/main/docs/tutorials/goldenpath_series/gp_module_two.md#introducing-a-server-controlled-network-variable), there's probably a few other issues that aren't as obvious in there which will end up painfully obvious to any new users who attempt to follow that tutorial)

Module 2, in particular, hasn't been updated since last October.

Might need to consider going over that, and updating it so it's actually applicable for v1.0.0 of Netcode for GameObjects.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
