### ISSUE TITLE
Feedback for ocs/migration/installation.md - Instructions for installing the official release package (v1.0.0)

### ISSUE THREAD

**Issue by 11BelowStudio** [Unity-Technologies/com.unity.multiplayer.docs#681]
This page hasn't been updated since the official v1.0.0 release of Netcode for GameObjects, and still presents the installation instructions to the user as 'how to install this WIP package', instead of a more reassuring 'how to install the release version of this package'.

If memory serves, it should be possible for users to just download the package via the Unity package manager now, so this page should just tell users to do that.

Alternatively, tell users to go to `/Packages/manifest.json`, then, in the `dependencies`, add `"com.unity.netcode.gameobjects": "1.0.0"`, like so:

```json
{
  "dependencies": {
     // everything else that's already in dependencies

    "com.unity.netcode.gameobjects": "1.0.0"
  },
  // other stuff that's in the manifest.json like scoped registries etc
}
```

But point is, this package is out of beta, with a v1.0.0 release version, so you may as well tell users to install the release version.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
