### ISSUE TITLE
Feedback for ocs/components/networkmanager.md

### ISSUE THREAD

**Issue by 11BelowStudio** [Unity-Technologies/com.unity.multiplayer.docs#687]
https://docs-multiplayer.unity3d.com/netcode/current/components/networkmanager#connecting

UNetTransport is pretty much deprecated, should provide an example using UnityTransport instead.

https://docs-multiplayer.unity3d.com/netcode/current/components/networkmanager#disconnecting

`StopHost()`, `StopClient()`, and `StopServer()` don't exist nowadays either.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
