### ISSUE TITLE
Feedback for /docs/transport/workflow-client-server.md

### ISSUE THREAD

**Issue by LukeStampfli** [Unity-Technologies/com.unity.multiplayer.docs#69]
**Provide Feedback on Docs**
Create minimal client and server tutorials use obsolete API and thus don't work.
`var writer = m_Driver.BeginSend(NetworkPipeline.Null, m_Connections[i]);` should probably be: `                    m_Driver.BeginSend(m_Connections[i], out DataStreamWriter writer);`. (need someone working on UTP to verify this as I have no idea what I'm doing) (Issue is present in both ClientBehaviour and ServerBehaviour in both the tutorial and the source files)

Also it would be nice to know what the int which `BeginSend` returns represents. The API docs say it's undocumented.

**About the site:**
What would you like to see on the website?

**Comment by s-omeilia-unity** [comment]
User concern still found in current and develop documentation. Worth a revisit and created a Jira for tracking.

**Comment by Briancoughlin** [comment]
Has been added to the backlog will be addressed in future update. Thanks for your contribution

**Comment by s-omeilia-unity** [comment]
@simon-lemay-unity I want to double-check before closing this out, but was this covered by your updates to BeginSend recently?

https://docs-multiplayer.unity3d.com/transport/1.0.0/minimal-workflow#client-update-loop

**Comment by s-omeilia-unity** [comment]
Thank you!
