### ISSUE TITLE
Feedback for ocs/tutorials/helloworld/helloworldintro.md - Faulty ':::important' and ':::tip' things

### ISSUE THREAD

**Issue by 11BelowStudio** [Unity-Technologies/com.unity.multiplayer.docs#700]
So, I've just realized that the `:::important ... :::` and `:::tip ... :::` things I added in #683 aren't rendered correctly (instead of having the correct tooltip formatting box around the content, they're shown as the raw text, with the `:::` bits also as raw text). Specifically, these two:

https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/1771acdae11deb009c9ce995ef1fe0c6f35282c2/docs/tutorials/helloworld/helloworldintro.md?plain=1#L11-L13 
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/1771acdae11deb009c9ce995ef1fe0c6f35282c2/docs/tutorials/helloworld/helloworldintro.md?plain=1#L105-L107

I thought I had formatted them correctly (like the other `:::important` in this page and other `:::note`s throughout the documentation), turns out that I probably did something wrong. Not sure why they're broken, but it might be best if someone who knows what they're doing with them can fix them.

**Comment by chrispope** [comment]
Renders correctly on the website: https://docs-multiplayer.unity3d.com/netcode/current/tutorials/helloworld

**Comment by 11BelowStudio** [comment]
> Renders correctly on the website: https://docs-multiplayer.unity3d.com/netcode/current/tutorials/helloworld

no, not really

see https://docs-multiplayer.unity3d.com/netcode/current/tutorials/helloworld/index.html#adding-your-scene-to-the-build

![image](https://user-images.githubusercontent.com/60523642/193954897-119c1142-f1e3-4ae2-a22e-c3f4d7d060d5.png)

**Comment by chrispope** [comment]
Apologies, I missed that one. Fixed now and live on the site.
