### ISSUE TITLE
Feedback for /wiki: Many dead links, still labelled as 'MLAPI' (also content may be mildly outdated)

### ISSUE THREAD

**Issue by 11BelowStudio** [Unity-Technologies/com.unity.multiplayer.docs#701]
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/wiki needs an update.

# 'Home' page

* 'Contacting Unity Docs' section
  * Link that says `Join the MLAPI Discord`
    * Should say `Join the Unity Multiplayer Networking Discord`
    * Should link to the aforementioned Unity Multiplayer Networking discord server (currently a dead link to discord.mlapi.network)
      * Like so: `Join the [Unity Multiplayer Networking Discord](http://discord.gg/unity-multiplayer-network)`
  * Mention of `... and help with requests for documentation (RFD)`
    * The link that says `request for documentation (RFD)` is dead.
      * Links to a nonexistent `com.unity.multiplayer.rfds` repository
      * Not sure what that repository was meant to contain, so please either update the link to point to whatever the successor of that repository was, or remove that link.

# 'About Versioning' page

* Still says MLAPI instead of Netcode for GameObjects

# 'Contributing Content' page

* 'Add a page using Github' section
  * All the links are to the `master` branch, instead of the `main` branch. `master` was last updated in November 2021, and is significantly behind `main`. Replace these links to refer to `main`.

# 'Working with Markdown' page

* Almost all links to templates are dead.
  * The only one that isn't dead is the one saying `All previews of templates are [on the site].`
* Thing that says 'Coming Soon! Templates for content (April 2021)'
  * Do those templates exist yet? If so, provide links to them.

# 'Building Locally' page

* Discord link at the bottom of the page is a dead link (still sends people to `discord.mlapi.network`)

# In general

* Still says MLAPI
* Discord links are all dead links to discord.mlapi.network instead of discord.gg/unity-multiplayer-network
* Many dead links
* Also worth going over it further to see if the specific technical content is still accurate or not, seeing as it hasn't been updated in over a year.

Anywho, would open a pull request to try fixing it myself, but it doesn't look like it's possible to open pull requests for wikis.

**Comment by armstrongl** [comment]
Closing this issue since we're no longer maintaining the wiki.
