### ISSUE TITLE
Feedback for /docs/mlapi-basics/networkobject.md

### ISSUE THREAD

**Issue by schraf** [Unity-Technologies/com.unity.multiplayer.docs#71]
**Provide Feedback on Docs**
There is a reference to component called NetworkTransfor on this page. I am assuming that is a misspelling and supposed to be NetworkTransfer? I also don't see any reference to a NetworkTransfer (or NetworkTransfor) in the api docs or the code repository for mlapi.

**Specific page:**
/docs/mlapi-basics/networkobject.md

**About the site:**
A clarification on the spelling of NetworkTransfor and some other references to what the component is.

**Comment by LukeStampfli** [comment]
This should be `NetworkTransform`

**Comment by lkrell** [comment]
Completed. Will be live with release.
