### ISSUE TITLE
Feedback for ocs/learn/clientside-interpolation.md

### ISSUE THREAD

**Issue by PK268** [Unity-Technologies/com.unity.multiplayer.docs#712]
The snippets provided for this article are stuck on "Loading..." this is because the script linked at ([https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/main/Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs#L335-L353](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/main/Assets/BossRoom/Scripts/Client/Game/Character/ClientCharacterVisualization.cs#L335-L353)) does not exist anymore.

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
