### ISSUE TITLE
Feedback for ocs/learn/faq.md

### ISSUE THREAD

**Issue by Cem-Kaya** [Unity-Technologies/com.unity.multiplayer.docs#720]
In the question "How do I join from two devices on the same network?"  the "NetworkManagerHud" link is dead 

It should probably be 
✅   [NetworkManagerHud](https://github.com/Unity-Technologies/multiplayer-community-contributions/blob/main/com.community.netcode.extensions/Runtime/NetworkManagerHud/NetworkManagerHud.cs)
instead of  
❌ [NetworkManagerHud](https://github.com/Unity-Technologies/mlapi-community-contributions/blob/main/com.mlapi.contrib.extensions/Runtime/NetworkManagerHud/NetworkManagerHud.cs)

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
