### ISSUE TITLE
Docs is broken

### ISSUE THREAD

**Issue by AnotherNulLe0** [Unity-Technologies/com.unity.multiplayer.docs#723]
### NetCode docs

[NetCode docs](https://docs-multiplayer.unity3d.com/netcode/current/about) contains broken redirects.

### NetCode tutorial
Some links in [Unity multiplayer networking](https://docs-multiplayer.unity3d.com/) is not working
Link https://docs-multiplayer.unity3d.com/netcode/current/tutorials/helloworld/helloworldintro in this site is not working and shows "Page Not Found" error

Sorry if I did something wrong, I just don't know where I can send this report

Here's screenshot of problem
![image](https://user-images.githubusercontent.com/44111820/183232453-0b47f1e9-d810-4f89-92a8-1e2bd3d43457.png)

**Comment by BrainNotFoundException** [comment]
I've put in a pull request regarding this issue you'll have to wait till its merged or so

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
