### ISSUE TITLE
Feedback for ocs/basics/maxnumberplayers.md

### ISSUE THREAD

**Issue by Grave18** [Unity-Technologies/com.unity.multiplayer.docs#728]
**Broken links and code preview**

![image](https://user-images.githubusercontent.com/5678288/183623401-655a71dc-805e-4022-960e-81bdf88cf2c4.png)

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.

**Comment by Grave18** [comment]
I made a pull request which fixes a typo in the github link.
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/765
