### ISSUE TITLE
Feedback for ocs/advanced-topics/inscene_parenting_player.md

### ISSUE THREAD

**Issue by atlz253** [Unity-Technologies/com.unity.multiplayer.docs#730]
**Describe the bug:**
Host player object parenting does not work by following the guide step by step. The guide is outdated.

**Steps to reproduce the behavior:**
1. Follow the guide step by step;
2. Fix SceneEventType name. As I understood SceneEventData.SceneEventTypes.C2S_SyncComplete now called SceneEventType.SynchronizeComplete https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/commit/67ec68f80ec495830a8144b2107fa4529b1917c2;
3. Start the host first and then the client;
4. See client soft synchronization error.

**Expected behavior:**
Two player objects are nested in the "Players" object on the host and client.

**Screenshots**
Host + client ❌
![image](https://user-images.githubusercontent.com/29949782/183851227-41bb2bbd-ef13-49d9-93c7-db832a9fa6dd.png)

Server + 2 clients ✔
![image](https://user-images.githubusercontent.com/29949782/183872567-bc5452b7-5478-4db8-9a44-d05fc841144f.png)

**Desktop:**
 - OS: Windows 11 Pro 21H2
 - Netcode version 1.0.0
 - Unity version 2021.3.7f1

**Additional info:**
A synchronization error occurs on line 13 ParentPlayerToInSceneNetworkObject.cs, but I have no idea how to fix it.

I have created a small project to test this error https://github.com/atlz253/ParentPlayerTest.git

**Comment by armstrongl** [comment]
Hi @atlz253, thanks for the detailed issue report. I'm going to try to replicate this issue today. I'll follow up soon 🙂

**Comment by armstrongl** [comment]
Hi @atlz253! This documentation is indeed outdated. We're working on updating it and will push out a fix soon.

**Comment by s-omeilia-unity** [comment]
This documentation was updated Feb 2 by Larah Armstrong.
