### ISSUE TITLE
Feedback for ocs/about.md

### ISSUE THREAD

**Issue by 7FULL** [Unity-Technologies/com.unity.multiplayer.docs#732]
Im sorry but the links doesnt work (the links like install unity network por upgrading mine por the classes none of them work)

Sorry for my english

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
