### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by MoldySurvivor** [Unity-Technologies/com.unity.multiplayer.docs#735]
On Module Two, ClientNetworkVariable is never declared. 
![Screen Shot 2022-08-13 at 11 06 24 AM](https://user-images.githubusercontent.com/49739298/184499892-0d3e9a3d-7390-4376-b3f2-67930ca12e99.png)

**Comment by JacobChrist** [comment]
duplicate of #721, there are older issues that appear similar but they have been closed.
