### ISSUE TITLE
Broken links thread

### ISSUE THREAD

**Issue by RainbowDoge** [Unity-Technologies/com.unity.multiplayer.docs#739]
On site: https://docs-multiplayer.unity3d.com/netcode/current/about

The following follow-up sites hyperlinked leads to "Page Not Found":
**Getting Started**
_Install Unity Netcode_ - [https://docs-multiplayer.unity3d.com/netcode/current/migration/installation.md](https://docs-multiplayer.unity3d.com/netcode/current/migration/installation.md)
_Migration from UNet to Netcode_ - [https://docs-multiplayer.unity3d.com/netcode/current/migration/migratingtonetcode.md
](https://docs-multiplayer.unity3d.com/netcode/current/migration/migratingtonetcode.md)_Upgrade to Unity Netcode Package_ -  [https://docs-multiplayer.unity3d.com/netcode/current/migration/migratingfrommlapi.md](https://docs-multiplayer.unity3d.com/netcode/current/migration/migratingfrommlapi.md)

**Hello World**
_Your First Networked Game_ - [https://docs-multiplayer.unity3d.com/netcode/current/tutorials/helloworld/helloworldintro](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/helloworld/helloworldintro)
_Building on "Hello World"_ - [https://docs-multiplayer.unity3d.com/netcode/current/tutorials/helloworld/helloworldtwo](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/helloworld/helloworldtwo)

**Golden Path**
_Foundation Module_ - [https://docs-multiplayer.unity3d.com/netcode/current/tutorials/goldenpath_series/goldenpath_foundation_module.md](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/goldenpath_series/goldenpath_foundation_module.md)

**Core Concept**
_Networking_ - [https://docs-multiplayer.unity3d.com/netcode/current/getting-started/connection-approval.md](https://docs-multiplayer.unity3d.com/netcode/current/getting-started/connection-approval.md)
_Scenes_ - [https://docs-multiplayer.unity3d.com/netcode/current/basics/scene-management.md](https://docs-multiplayer.unity3d.com/netcode/current/basics/scene-management.md)

**Learn More**
_References_ - [https://docs-multiplayer.unity3d.com/netcode/current/learn/index.md](https://docs-multiplayer.unity3d.com/netcode/current/learn/index.md)
_Boss Room_ - [https://docs-multiplayer.unity3d.com/netcode/current/learn/getting-started-boss-room.md](https://docs-multiplayer.unity3d.com/netcode/current/learn/getting-started-boss-room.md)
_Bite Size Samples_ - [https://docs-multiplayer.unity3d.com/netcode/current/learn/bitesize-introduction.md](https://docs-multiplayer.unity3d.com/netcode/current/learn/bitesize-introduction.md)

**Comment by s-omeilia-unity** [comment]
All docs content for the Unity Multiplayer Networking docs site has been reviewed in a docs audit. This includes link updates, content review by development to be up-to-date as of Aug 2022, and content rewrites. If your issue remains, please open a new GH issue to capture your concern. Thank you.
