### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by onurigdi** [Unity-Technologies/com.unity.multiplayer.docs#746]
NetworkVariableTest.cs script is use ClientNetworkVariable but there is no declaration of it.

**Comment by JacobChrist** [comment]
duplicate of #721, there are older issues that appear similar but they have been closed.

**Comment by chrispope** [comment]
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/802
