### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by nuehado** [Unity-Technologies/com.unity.multiplayer.docs#756]
ClientNetworkVariable not defined in NetworkVariableTest script

**Comment by JacobChrist** [comment]
duplicate of #721, there are older issues that appear similar but they have been closed.

**Comment by chrispope** [comment]
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/802
