### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by ochinski** [Unity-Technologies/com.unity.multiplayer.docs#762]
Reference: 
https://docs-multiplayer.unity3d.com/netcode/current/tutorials/goldenpath_series/goldenpath_two#introducing-a-server-controlled-network-variable

As you follow along the project continued from "golden path one", we are introduced to using network variables. 

A random variable is introduced: `ClientNetworkVariable.Value` where there is no reference to the creation of this var. Continuing past that the server _only_ transforms the player, where the client player transform remains still. Seems to be missing context inbetween this.

**Comment by JacobChrist** [comment]
duplicate of #721, there are older issues that appear similar but they have been closed.
