### ISSUE TITLE
Header font appears blurry

### ISSUE THREAD

**Issue by vertxxyz** [Unity-Technologies/com.unity.multiplayer.docs#764]
**Steps to reproduce the behavior:**
1. Go to any page and look at its header fonts.
2. Note how they appear blurry, and not displayed crisply.  **h5** is a particularly heinous example.

**Expected behavior:**
The header fonts appear crisp, and well aliased.

**Screenshots**

![image](https://user-images.githubusercontent.com/21963717/171385045-cd5b77b7-130d-49e0-8b1c-e12748c4cc40.png)

The **left** is what I see when using the site.
The **right** is after I've fixed the header font, (and poorly adjusted padding and header size to fix the annoying grouping of content, another issue that should probably be fixed).

![image](https://user-images.githubusercontent.com/21963717/171382432-cddc17dc-78c4-45c3-b873-a13081778c3b.png)

**Platform:**
 - OS: Windows
 - Browser: Vivaldi & Edge
 - Version: 5.2.2623.48 & 101.0.1210.53
 
**Additional info:**
My fix involves embedding the [Bold 700](https://fonts.google.com/share?selection.family=Roboto:wght@700) version of Roboto into the page's header:
```<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@700&amp;display=swap" rel="stylesheet">
```

Work your own web developer magic though.

**Comment by armstrongl** [comment]
Hi @vertxxyz, I tried replicating this issue but couldn't with Chrome on Windows 10. 

By the way, we're currently at a crossroads in determining how to proceed with the documentation site, so the tooling will likely change shortly. We might even have the multiplayer technology documentation hosted with the rest of the Unity documentation on docs.unity.com. Keep an eye on Discord for updates 🙂

**Comment by vertxxyz** [comment]
That's good to hear regardless, hopefully it's a modernisation, docs as code.
I'm one of the authors of this plug-in, so I've got to keep an eye on your work
https://github.com/Developer-Notes-Extension
