### ISSUE TITLE
Feedback for ocs/components/networktransform.md

### ISSUE THREAD

**Issue by mattlol85** [Unity-Technologies/com.unity.multiplayer.docs#766]
Misspelling of the word "regular" in the diagram @

https://docs-multiplayer.unity3d.com/img/BufferedTick_Dark.png

**Comment by SamuelBellomo** [comment]
@jilfranco-unity bottom bubble, it says "reular"

**Comment by armstrongl** [comment]
Hi @mattlol85 ! Thanks for raising this issue. It looks like this issue was fixed in a previous PR 🙂
