### ISSUE TITLE
Feedback for ocs/components/networkanimator.md - doesn't work?

### ISSUE THREAD

**Issue by LiterallyWar** [Unity-Technologies/com.unity.multiplayer.docs#770]
Getting 
> error CS0246: The type or namespace name 'NetworkAnimator' could not be found (are you missing a using directive or an assembly reference?)

despite having
```cs
using UnityEngine;
using Unity.Netcode;
```

what's up?

**Comment by LiterallyWar** [comment]
issue solved for me personally at https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/issues/2186

**Comment by armstrongl** [comment]
Hi @LiterallyWar! Thanks for opening this issue. I'm glad the engineering team was able to help you out. I'll add a note to the docs regarding this with #938 🙂
