### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by R1G** [Unity-Technologies/com.unity.multiplayer.docs#772]
The code snippet for `NetworkVariable.cs` under the section **Introducing a Server-controlled Network Variable** does not declare any NetworkVariable named `ClientNetworkVariable` and thus fails to compile.

**Comment by JacobChrist** [comment]
duplicate of #721, there are older issues that appear similar but they have been closed.
