### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by FerryPJ** [Unity-Technologies/com.unity.multiplayer.docs#775]
The NetworkVariableTester code does not compile as is because the ClientNetworkVariable is not defined

**Comment by christianju-grz** [comment]
[Updated documentation for Golden Path 2](https://docs-multiplayer.unity3d.com/netcode/0.1.0/tutorials/goldenpath_series/goldenpath_two/index.html)

**Comment by chrispope** [comment]
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/802
