### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by noobogami** [Unity-Technologies/com.unity.multiplayer.docs#777]
in script of this part [Introducing a Server-controlled Network Variable](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/goldenpath_series/goldenpath_two/index.html#introducing-a-server-controlled-network-variable) you have a parameter called `ClientNetworkVariable` in 
`Debug.Log("Server set its var to: " + ServerNetworkVariable.Value + ", has client var at: "  + ClientNetworkVariable.Value);`
that is not defined in script.

**Comment by christianju-grz** [comment]
[Updated documentation for Golden Path 2](https://docs-multiplayer.unity3d.com/netcode/0.1.0/tutorials/goldenpath_series/goldenpath_two/index.html)

**Comment by chrispope** [comment]
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/802
