### ISSUE TITLE
Feedback for ocs/tutorials/helloworld.md

### ISSUE THREAD

**Issue by LaurieCheers-unity** [Unity-Technologies/com.unity.multiplayer.docs#780]
Speaking as an experienced Unity user, I found this instruction confusing:
Back in the Editor, select File > Build Settings > Player Settings.... Beneath Settings for PC, Mac, & Linux Standalone, click Resolution and Presentation to open the section options.

The "Player Settings" button is hard to find at the bottom of this window, and the Build Settings window itself has a "Windows, Mac, Linux" section, making it quite easy to be confused about where you're supposed to be looking. I suggest this would be clearer as:
Back in the Editor, open Edit -> Project Settings and select the Player tab. Beneath Settings for PC, Mac, & Linux Standalone ...

**Comment by chrispope** [comment]
I like the suggestion, I will change it. Thanks @LaurieCheers-unity
