### ISSUE TITLE
Feedback for ocs/advanced-topics/object-pooling.md

### ISSUE THREAD

**Issue by AnomalousUnderdog** [Unity-Technologies/com.unity.multiplayer.docs#781]
The given sample `NetworkObjectPool.cs` code from a project called Boss Room was a bit confusing since it was out of context. I submitted [an issue](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/issues/733) on it without realizing the documentation itself here also has a submit issue feature. I only noticed it just now, so I'm adding this here to notify those it may concern.

The sample code initializes the pool only once then never again. That leads to a problem where if the server is shutdown, then started again for a 2nd time, it won't work correctly anymore. You'll get a KeyNotFoundException when trying to instantiate a pooled prefab when the server is started a 2nd time, because at that point, the `_pooledObjects` Dictionary has been cleared when the server was shut down, but was not reinitialized when the server was restarted.

The Boss Room devs explained that this code is meant to be used inside a specific scene only, and the scene must be unloaded upon server shutdown, to ensure a clean state each time. But for sample code meant to teach newcomers to Netcode for GameObjects, I think that should be clarified somehow, or use a different code example.

I'd also love to see a sample code for this that properly uses the existing [ObjectPool](https://docs.unity3d.com/ScriptReference/Pool.ObjectPool_1.html) class instead of handling your own Queue.

**Comment by chrispope** [comment]
Addressed in the Boss Room repo here: https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/issues/733
