### ISSUE TITLE
ClientNetworkVariable in the Golden Path Module Two is not present in the code

### ISSUE THREAD

**Issue by Cipher88** [Unity-Technologies/com.unity.multiplayer.docs#782]
Link: 
https://docs-multiplayer.unity3d.com/netcode/current/tutorials/goldenpath_series/goldenpath_two/index.html#introducing-a-server-controlled-network-variable

The client's network variable is not defined for the client side of the network variable test.
Someone please correct it as it is causing confusion.

**Comment by christianju-grz** [comment]
[Updated documentation for Golden Path 2](https://docs-multiplayer.unity3d.com/netcode/0.1.0/tutorials/goldenpath_series/goldenpath_two/index.html)

**Comment by chrispope** [comment]
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/802
