### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by caduzeraa** [Unity-Technologies/com.unity.multiplayer.docs#784]
Somehow after following the step where we edit the NetworkVariableTest.cs file I got an error:
`Assets\Scripts\NetworkVariableTest.cs(28,21): error CS0103: The name 'ClientNetworkVariable' does not exist in the current context`

Am I missing something or is it an actual error?

**Comment by christianju-grz** [comment]
[Updated documentation for Golden Path 2](https://docs-multiplayer.unity3d.com/netcode/0.1.0/tutorials/goldenpath_series/goldenpath_two/index.html)

**Comment by JacobChrist** [comment]
duplicate of #721, there are older issues that appear similar but they have been closed.

**Comment by chrispope** [comment]
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/802
