### ISSUE TITLE
Description is erroneous! - Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by docdact** [Unity-Technologies/com.unity.multiplayer.docs#793]
Description is erroneous!

Testing Server-controlled Network Variables doesn't work.
ClientNetworkVariable.Value is not implemented.

Isn't described: [Testing the command line helper](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/goldenpath_series/goldenpath_two#testing-the-command-line-helper).

**Comment by chrispope** [comment]
https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/802
