### ISSUE TITLE
Feedback for /docs/tutorials/helloworldintro.md

### ISSUE THREAD

**Issue by Briancoughlin** [Unity-Technologies/com.unity.multiplayer.docs#81]
**Provide Feedback on Docs**
Enter feedback for any of the following. If you meant to enter a bug, select Issues then Bug Report. 
Comment from Discord
Whyser — 03/20/2021
I really don't think people need to know, in a networking tutorial how to clear the Editor Console (https://mp-docs.dl.it.unity3d.com/docs/tutorials/helloworldintro) "NOTE
You may see the following error reported [...]". And most definitely not a video/gif showing it :joy:. Just writing that it can be ignored should be enough ^^

**Specific page:**
If you clicked Log an issue through the site, the doc file is in the issue title. Or add a link to the page you want to give feedback on.

**About the site:**
What would you like to see on the website?

**Comment by Briancoughlin** [comment]
Changes proposed in PR 'Update helloworldintro.md #82' issue can be closed once PR merged

**Comment by lkrell** [comment]
Complete.
