### ISSUE TITLE
How to verify expected test results: ocs/tutorials/helloworld.md

### ISSUE THREAD

**Issue by docdact** [Unity-Technologies/com.unity.multiplayer.docs#815]
Testing Hello World[#](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/helloworld#testing-hello-world)
Now we will test to see if everything works as expected.

Click Play.
Click Start Host under NetworkManager.

The Problem:
Yes, I click Play, Yes, I click Host under NetworkManager.
But what should happen? I don't see anything, except a plane.
What is the point of this tutorial? How to identify what is expected?

**Comment by armstrongl** [comment]
Hi @docdact ! Thanks for reporting this. We addressed this issue in the Hello World rewrite. You can check it out [here](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/get-started-ngo).
