### ISSUE TITLE
Feedback for ocs/api/Unity.Netcode.NetworkBehaviourReference.md

### ISSUE THREAD

**Issue by brainwipe** [Unity-Technologies/com.unity.multiplayer.docs#819]
Incomplete sentence in opening description:

> A helper struct for serializing NetworkBehaviours over the network. Can be used in RPCs and NetworkVariable\<T>. Note: network ids get recycled by the NetworkManager after a while. So a reference pointing to

I'm hoping that it reads:

> So a reference point to a network behaviour is more more reliable as it is not recycled.

Because that's the functionality I need. 😁

**Comment by armstrongl** [comment]
Hi @brainwipe, thanks for opening this issue. I'm pushing out a fix with #938 🙂
