### ISSUE TITLE
Results not identical ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by docdact** [Unity-Technologies/com.unity.multiplayer.docs#821]
Section: Testing Server-controlled Network Variables
1. First of all, nothing to see at the console. Why?
2.  At the server.log is logged the following:
UnloadTime: 0.826300 ms
Server's var initialized to: 0
Server set its var to: 0,3
Server set its var to: 7,599995
Server set its var to: 14,90002
Server set its var to: 22,20005
Server set its var to: 29,50008
Server set its var to: 36,80001
But not:
Server's var initialized to: 0
Server set its var to: 0.1, has client var at: 0
Server set its var to: 3.099999, has client var at: 2.6
Server set its var to: 6.099997, has client var at: 5.599997

**Comment by LPLafontaineB** [comment]
Thank you for reporting this issue, it has now been fixed in our develop branch
