### ISSUE TITLE
need update for docs/basics/maxnumberplayers.md

### ISSUE THREAD

**Issue by Scincy** [Unity-Technologies/com.unity.multiplayer.docs#823]
Document [Limiting the maximum number of players](https://docs-multiplayer.unity3d.com/netcode/current/basics/max-players) needs to be updated. The example that included at document no longer exisist and the variable that saving maximum player count is in diffrent Script ([Assets/Scripts/ConnectionManagement/ConnectionManager.cs](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/9bdfe99812be3987fa96fe7cc893eaca66cfa0d8/Assets/Scripts/ConnectionManagement/ConnectionManager.cs#L73)).

and the example of `how to handle limiting the number of players through the connection approval process` is in [Assets/Scripts/Gameplay/GameState/ServerCharSelectState.cs Line number 223 int `GetAvailablePlayerNumber()`](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/9bdfe99812be3987fa96fe7cc893eaca66cfa0d8/Assets/Scripts/Gameplay/GameState/ServerCharSelectState.cs#L223)

**Comment by armstrongl** [comment]
Hi @Scincy ! Thanks for opening this issue! I'm going to be merging a fix for this in #938 🙂
