### ISSUE TITLE
Feedback for ocs/learn/rpcvnetvar.md

### ISSUE THREAD

**Issue by Stevenpc3** [Unity-Technologies/com.unity.multiplayer.docs#828]
https://docs-multiplayer.unity3d.com/netcode/current/learn/rpcvnetvar/index.html  Does not load code examples.  LInks to Github show a 404.

![image](https://user-images.githubusercontent.com/6076207/196053963-b46dc598-873a-425b-979b-315d18363dfa.png)

![image](https://user-images.githubusercontent.com/6076207/196053977-9dfe9896-a27a-4a24-9377-c0f9de44ae05.png)

**Comment by armstrongl** [comment]
Hi @Stevenpc3 ! This issue has been resolved 🙂
