### ISSUE TITLE
Feedback for ocs/relay/relay.md

### ISSUE THREAD

**Issue by HernandoNJ** [Unity-Technologies/com.unity.multiplayer.docs#833]
Missing commas and requesting improve in coding presentation
type:bug
stat:awaiting response
Link: https://docs-multiplayer.unity3d.com/netcode/current/relay/relay/index.html 

RelayHostData data = new RelayHostData
    {
        // WARNING allocation.RelayServer is deprecated
        IPv4Address = allocation.RelayServer.IpV4 **--> comma missing**
        Port = (ushort) allocation.RelayServer.Port,**--> remove next blank line**
                                                                            
        

        AllocationID = allocation.AllocationId,
        AllocationIDBytes = allocation.AllocationIdBytes,
        ConnectionData = allocation.ConnectionData,
        Key = allocation.Key,
    };

The same happens for `RelayJoinData data = new RelayJoinData`

**Comment by armstrongl** [comment]
Hi @HernandoNJ, thanks for reporting this issue. I'll push out a fix with #938 🙂
