### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by pidez** [Unity-Technologies/com.unity.multiplayer.docs#835]
Hello, in the NetworkVariableTest.cs script i don't see the log for ", has client var at: xxx" in fact when i run the game inside unity i only see the value for the server. Furthermore, if i run the game from the windows command line(client and server together) i don't know where to look for the log messages!

**Comment by manuelhuber** [comment]
Looks like the code sample under ["Introducing a Server-controlled Network Variable"](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/blob/e5ff01c3aca814e4c51bcc9f1e57716676076a87/versioned_docs/version-0.1.0/tutorials/goldenpath_series/gp_module_two.md) is outdated

**Comment by chrispope** [comment]
HelloWorld and GoldenPath 1&2 have been removed and replaced with a "getting started with NGO guide"
