### ISSUE TITLE
Feedback for ocs/api/Unity.Netcode.NetworkObject.md

### ISSUE THREAD

**Issue by JesseOlmer** [Unity-Technologies/com.unity.multiplayer.docs#837]
This page is missing from the API Ref side-nav

**Comment by JesseOlmer** [comment]
Also looks like maybe it hasn't been regenerated in a while? The page says "Assembly: MLAPI.dll" which isn't an assembly in the codebase for a number of months/releases now.

**Comment by armstrongl** [comment]
Hi @JesseOlmer! I'll be rolling out a fix for this soon (along with regenerating the SDK documentation). Thanks for opening this issue 🙂
