### ISSUE TITLE
Github link is broken

### ISSUE THREAD

**Issue by CaiporaGames** [Unity-Technologies/com.unity.multiplayer.docs#84]
**Describe the bug:**
The link: 
 https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi.git?path=/com.unity.multiplayer.mlapi#develop 
is moving me to the 404 page. The unity editor can not download the files

**Steps to reproduce the behavior:**
1. Go to this page: https://docs-multiplayer.unity3d.com/docs/tutorials/helloworldintro
2. Click on this link: https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi.git?path=/com.unity.multiplayer.mlapi#develop
3. See error: 404 page

**Expected behavior:**
The github page with the MLAPI

**Desktop/Tablet/Smartphone (please complete the following information):**
 - Windows
 - Browser chrome

**Comment by Briancoughlin** [comment]
The site is prerelease so that link is not correct at the present time. Links and pages are being updated with release information.

**Comment by JesseOlmer** [comment]
The link at this location in the documentation will likely never be one you can click on and visit in a web browser. It is a custom extension of git URLs for the Unity Package Manager which allows information about the repo, path within the repo,  branch or tag information, and protocol to be communicated as a single address.

**Comment by lkrell** [comment]
Surrounding the link with code ticks to ensure it is copied/pasted not clickable. Intent is to copy/paste. Handled in PR #83
