### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_two.md

### ISSUE THREAD

**Issue by NiceYellowEgg** [Unity-Technologies/com.unity.multiplayer.docs#841]
This page seems to be missing some important code compared to the previous version 0.1.0

https://docs-multiplayer.unity3d.com/netcode/0.1.0/tutorials/goldenpath_series/goldenpath_two

Specifically:

  else if (IsClient)
        {
            ClientNetworkVariable.Value = 0.0f;
            Debug.Log("Client's var initialized to: " + ClientNetworkVariable.Value);
        }

etc

**Comment by NiceYellowEgg** [comment]
actually, looking at the detail it appears that the output is misleading:

```
Server's var initialized to: 0
Server set its var to: 0.1, has client var at: 0
Server set its var to: 3.099999, has client var at: 2.6
Server set its var to: 6.099997, has client var at: 5.599997
```

The "has client var at: 0" should probably be removed as I believe the old 0.1.0 code won't work anymore. As clients can no longer write to network variables and the second part goes into RPC calls instead.

**Comment by NiceYellowEgg** [comment]
Something like this seems more appropriate:

`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Unity.Netcode;

public class NetworkVariableTest : NetworkBehaviour
{
    private NetworkVariable<float> ServerNetworkVariable = new();
    private float last_t = 0.0f;

    public override void OnNetworkSpawn()
    {
        if (IsServer)
        {
            ServerNetworkVariable.Value = 0.0f;
            Debug.Log("Server's var initialized to: " + ServerNetworkVariable.Value);
        }
        else if (IsClient)
        {
            Debug.Log("Client says the Server's var initialised to: " + ServerNetworkVariable.Value);
        }
    }

    // Update is called once per frame
    void Update()
    {
        var t_now = Time.time;
        if (IsServer)
        {
            ServerNetworkVariable.Value += 0.1f;
            if (t_now - last_t > 0.5f)
            {
                last_t = t_now;
                Debug.Log("Server set its var to: " + ServerNetworkVariable.Value);
            }
        }
        else if (IsClient)
        {            
            if (t_now - last_t > 0.5f)
            {
                last_t = t_now;
                Debug.Log("Client says the Server's var is updated to: " + ServerNetworkVariable.Value);
            }
        }
    }
}`

`Client says the Server's var initialised to: 0
Client says the Server's var is updated to: 0
Client says the Server's var is updated to: 3.099999
Client says the Server's var is updated to: 6.099997'

**Comment by chrispope** [comment]
HelloWorld and GoldenPath 1&2 have been removed and replaced with a "getting started with NGO guide"
