### ISSUE TITLE
Feedback for ools/runtime-stats-monitor.md

### ISSUE THREAD

**Issue by jorrit-de-vries** [Unity-Technologies/com.unity.multiplayer.docs#846]
The documentation misses the information that the runtime NetStatsMonitor components is only available in 2021.2+. One can figure this out when looking at the constraints of the .asmdef file.

**Comment by armstrongl** [comment]
Hi @jorrit-de-vries ! Thanks for reporting this. I'll fix this in my next PR 🙂
