### ISSUE TITLE
Feedback for ocs/basics/maxnumberplayers.md

### ISSUE THREAD

**Issue by yoangau** [Unity-Technologies/com.unity.multiplayer.docs#849]
Dead link  and code not loading
> See full example on [GitHub](https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/blob/main/Assets/Scripts/Gameplay/ConnectionManagement/ServerGameNetPortal.cs#L176)

**Comment by armstrongl** [comment]
Hi @yoangau ! I'm looking into fixing this 🙂
