### ISSUE TITLE
Feedback for ocs/basics/scenemanagement/scene-events.md

### ISSUE THREAD

**Issue by evilotaku** [Unity-Technologies/com.unity.multiplayer.docs#859]
https://docs-multiplayer.unity3d.com/netcode/current/basics/scenemanagement/scene-events/index.html#synchronization

SceneEventType.SynchronizeComplete:
signifies that the client has finished loading all scenes and locally spawned all Netcode objects. The client sends this scene event message back to the server. This message also includes a list of NetworkObject.NetworkObjectIds for all of the NetworkObjects the client spawned.
SceneEventType.ReSynchronize:
signifies that the server determines the client needs to be "re-synchronized" because one or more NetworkObjects were despawned while the client was synchronizing. This message is sent to the client with a NetworkObject.NetworkObjectId list for all NetworkObjects the client needs to despawn.

The list of networkobjects referenced here does not seem to exist according to the API documentation

**Comment by armstrongl** [comment]
Hi @evilotaku ! Thanks for raising this issue. I'm getting clarification from the Netcode team on this. 🙂

**Comment by s-omeilia-unity** [comment]
Both of these NetworkObjects are listed in the API ref here: https://docs-multiplayer.unity3d.com/netcode/current/api/Unity.Netcode.SceneEventType

There may have been an update since you've posted that didn't get noted back here.
