### ISSUE TITLE
Feedback for ersioned_docs/version-1.0.0/basics/maxnumberplayers.md

### ISSUE THREAD

**Issue by HeaDiii** [Unity-Technologies/com.unity.multiplayer.docs#863]
The example code doesn't load. The linked GitHub page yields a 404 error.

**Comment by armstrongl** [comment]
Hi @HeaDiii ! Thanks for raising this issue. I'll address this in https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/904. 🙂
