### ISSUE TITLE
Diagram missing in ocs/basics/scenemanagement/timing-considerations.md

### ISSUE THREAD

**Issue by dstears-git** [Unity-Technologies/com.unity.multiplayer.docs#870]
In the beginning of the Client Synchronization section has text that references a diagram, but the page does not have any diagram between these two paragraphs.

"The below diagram, Client Synchronization Updates, steps you through the entire client synchronization process from starting the client all the way to the client being fully synchronized and connected.

Above, we can see..."

**Comment by armstrongl** [comment]
Hi @dstears-git ! Thanks for raising this issue. Which version of the Netcode documentation is this issue on?

**Comment by dstears-git** [comment]
The version at the top of the page is 1.1.0. The rest of the text on the page mentions a few other diagrams that are missing as well.

If I switch to version 1.0.0 in the dropdown next to "Netcode for GameObjects", then I am able to see the diagrams.

Here is the relevant URL:
https://docs-multiplayer.unity3d.com/netcode/current/basics/scenemanagement/timing-considerations
