### ISSUE TITLE
Feedback for ocs/basics/networkvariable.md

### ISSUE THREAD

**Issue by evilotaku** [Unity-Technologies/com.unity.multiplayer.docs#872]
in the note in Permissions it states 
"IMPORTANT
Since Netcode for GameObjects uses a server authoritative model, the server will always have read or write permissions to any NetworkVariable. As an example, if you set both the read and write permissions to Owner the server can still read and write to the NetworkVariable."

This is incorrect as the Server will not have Write permission but will still have Read permission

**Comment by armstrongl** [comment]
Hi @evilotaku ! Thanks for raising this issue. I'm getting clarification from the Netcode team on this. 🙂

**Comment by armstrongl** [comment]
Hi @evilotaku, this is a valid issue, and I'll push up a fix with #938 🙂
