### ISSUE TITLE
Feedback for ocs/advanced-topics/message-system/rpc-params.md

### ISSUE THREAD

**Issue by nbaggett** [Unity-Technologies/com.unity.multiplayer.docs#876]
ServerRPCParams doc link is broken.

**Comment by armstrongl** [comment]
Hi @nbaggett ! Thanks for raising this issue. Which version of the Netcode documentation are you looking at? I just checked the most current version of this page and the [ServerRpcParams Documentation](https://docs-multiplayer.unity3d.com/netcode/current/api/Unity.Netcode.ServerRpcParams) link appears to be working.

**Comment by nbaggett** [comment]
The link takes me to this address when I left click it: https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/api/Unity.Netcode.ServerRpcParams

And this address when I middle mouse click it: https://docs-multiplayer.unity3d.com/netcode/current/api/Unity.Netcode.ServerRpcParams/index.html

**Comment by nbaggett** [comment]
Sorry I forgot to mention, It's the latest version of the docs.

**Comment by armstrongl** [comment]
Ah, I see. This is a bug in our version of Docusaurus. I haven't been able to pinpoint exactly why it happens, but I believe the only way to fix it is to upgrade the version. We're at a bit of a crossroads regarding docs tooling right now, and we might soon migrate the MTT documentation to docs.unity.com, which should resolve this (and similar) issues. Keep an eye on [Discord](https://discord.gg/buMxnnPvTb) for updates 🙂
