### ISSUE TITLE
Feedback for ocs/basics/connection-approval.md

### ISSUE THREAD

**Issue by Reag** [Unity-Technologies/com.unity.multiplayer.docs#882]
Can we get a basic example of how to use the Pending system? The provided examples in the Boss Room repo have far too much boilerplate for quick understanding.

For example, for testing purposes, I want to make a simple method that waits 5 seconds before approving a client request. However, the provided documentation is insufficient for me to accomplish this without playing around in the editor. While this is not a critical issue, I believe the documentation's examples should be updated to cover all basic use cases.

**Comment by armstrongl** [comment]
Hi @Reag ! Thanks for raising this issue. We plan to discuss expanding the Boss Room (and Bitesize) sample documentation to address more basic use cases in 2023. I'll make a note of your request 🙂.
