### ISSUE TITLE
Feedback for ocs/installation/migratingfrommlapi.md

### ISSUE THREAD

**Issue by mindworksarts** [Unity-Technologies/com.unity.multiplayer.docs#902]
[Package Manager Window] Cannot perform upm operation: Unable to add package [https://github.com/Unity-Technologies/mlapi-community-contributions.git?path=/com.unity.multiplayer.mlapi-patcher]:
  Cannot checkout repository [https://github.com/Unity-Technologies/mlapi-community-contributions.git] on target path [com.unity.multiplayer.mlapi-patcher]:
    Error when executing git command. error: pathspec 'com.unity.multiplayer.mlapi-patcher' did not match any file(s) known to git
 [NotFound].
 
 This is the error received when trying to add the patcher from git as instructed at 
 https://docs-multiplayer.unity3d.com/netcode/current/installation/upgrade_from_mlapi

**Comment by armstrongl** [comment]
@NoelStephensUnity do you know why this might be happening?

**Comment by NoelStephensUnity** [comment]
I think as opposed to this:
https://github.com/Unity-Technologies/mlapi-community-contributions.git?path=/com.unity.multiplayer.mlapi-patcher
It should be this:
https://github.com/Unity-Technologies/multiplayer-community-contributions.git?path=/com.unity.multiplayer.mlapi-patcher

The primary difference being the documentation still has **mlapi**-community-contributions and the updated/rebranded version is **multiplayer**-community-contributions.

I verified the patcher still exists in this location:
https://github.com/Unity-Technologies/multiplayer-community-contributions/tree/release-0.1.0/com.unity.multiplayer.mlapi-patcher
