### ISSUE TITLE
Feedback for ocs/tutorials/goldenpath_series/gp_module_one.md

### ISSUE THREAD

**Issue by mindworksarts** [Unity-Technologies/com.unity.multiplayer.docs#905]
The HelloWorldManager.cs returns this error:

The type or namespace name 'HelloWorldPlayer' could not be found (are you missing a using directive or an assembly reference?)

Not sure what I've done wrong here since I've followed the multiplayer tutorials step by step and everything was working from hello world. I am in Unity 2021.3.8f1.

**Comment by chrispope** [comment]
HelloWorld and GoldenPath 1&2 have been removed and replaced with a "getting started with NGO guide"
