### ISSUE TITLE
Feedback for ocs/advanced-topics/serialization/inetworkserializable.md

### ISSUE THREAD

**Issue by Chaddledee** [Unity-Technologies/com.unity.multiplayer.docs#907]
NetworkSerialize has to be public otherwise the error "'MyComplexStruct' does not implement interface member 'INetworkSerializable.NetworkSerialize<T>(BufferSerializer<T>)'." is produced.

In the first example NetworkSerialize is not public.

**Comment by armstrongl** [comment]
Hi @Chaddledee, I'm going to push out a fix for this with #938  🙂
