### ISSUE TITLE
Feedback for ocs/advanced-topics/message-system/rpc-params.md

### ISSUE THREAD

**Issue by cyraid** [Unity-Technologies/com.unity.multiplayer.docs#911]
Page not found for ServerRpcParams and ClientRpcParams. :)

**Comment by chrispope** [comment]
@cyraid https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/message-system/rpc-params - page is found for me clicking both [ServerRpcParams Documentation](https://docs-multiplayer.unity3d.com/netcode/current/api/Unity.Netcode.ServerRpcParams) & [ClientRpcParams Documentation](https://docs-multiplayer.unity3d.com/netcode/current/api/Unity.Netcode.ClientRpcParams)

**Comment by cyraid** [comment]
![20230117_043224](https://user-images.githubusercontent.com/7562753/212877029-fd8c8c8e-b755-47d0-b1a2-20fc94290af6.jpg)

Page not found when clicking on ServerRpcParams Documentation (https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/api/Unity.Netcode.ServerRpcParams) on https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/message-system/rpc-params/index.html

**Comment by cyraid** [comment]
If I tap on the link in the page, it gives me page not found. If I enter the url directly (https://docs-multiplayer.unity3d.com/netcode/current/api/Unity.Netcode.ServerRpcParams), it goes to the page.

**Comment by chrispope** [comment]
Thanks @cyraid - I have created a PR for this issue.

**Comment by chrispope** [comment]
Fix will be live shortly

**Comment by cyraid** [comment]
> Fix will be live shortly

Thanks Chris.
