### ISSUE TITLE
Feedback for /docs/mlapi-basics/networkvariable.md

### ISSUE THREAD

**Issue by Cosmin-B** [Unity-Technologies/com.unity.multiplayer.docs#92]
**Provide Feedback on Docs**
Please replace the NetworkVariablekedVar with NetworkVariable, in the example code snippet on that page.

**Comment by Briancoughlin** [comment]
PR created for the fix this issue can be closed once PR is approved and merged

**Comment by lkrell** [comment]
Finished, will be live today.
