### ISSUE TITLE
Feedback for documentation page

### ISSUE THREAD

**Issue by Raikir-i-sh** [Unity-Technologies/com.unity.multiplayer.docs#920]
When I press the new "Search icon" made by Algolia, the search popup shows up . Then while the search box is empty, if I press "up" arrow , everything blacks out & I have to reload the page again. 
I'm on Windows 10 and Opera Browser. 
![image](https://user-images.githubusercontent.com/47144864/212538098-fd789a3e-4417-49d4-b7d4-bb75c4322607.png)

**Comment by chrispope** [comment]
I just tested on Safari and Brave browsers and it works fine, maybe this is an Opera issue? Could you try another browser?

**Comment by armstrongl** [comment]
Hi @Raikir-i-sh, I tried to replicate this issue and wasn't able to. Are you still encountering it?
