### ISSUE TITLE
Feedback for ocs/tutorials/get-started-with-ngo.md

### ISSUE THREAD

**Issue by chrispope** [Unity-Technologies/com.unity.multiplayer.docs#929]
One of the screenshot images blurred out portions of the editor, however, no other screenshot images do this.
For consistency, we could remove the blurring screenshot and replace it with a non-blurred image.

https://discord.com/channels/449263083769036810/798150732141690900/1065572362872954913

**Comment by armstrongl** [comment]
I'm addressing this issue in #933 🙂
