### ISSUE TITLE
Feedback for ocs/tutorials/command-line-helper.md

### ISSUE THREAD

**Issue by jeffposey** [Unity-Technologies/com.unity.multiplayer.docs#931]
> C:\Users\sarao>HelloWorld\Build\HelloWorld.exe -logfile -log-server.txt -mode server & HelloWorld\Build\HelloWorld.exe -logfile log-client.txt -mode client

This sample command has an issue. There should not be a dash before "log-server.txt"

**Comment by armstrongl** [comment]
Hi @jeffposey ! Thanks again for providing all this feedback. I'm addressing this issue in #933 🙂
