### ISSUE TITLE
Feedback for ocs/tutorials/get-started-with-ngo.md

### ISSUE THREAD

**Issue by jeffposey** [Unity-Technologies/com.unity.multiplayer.docs#932]
NOTE: I tested with **Unity 2023.1.0a24.2386.2878**

DISCLAIMER: There is some nitpicky feedback included. Overall, great job!

### Structuring Suggestions

It feels like too much for one page. You might consider making RPCs another page to click "Next" to, and then
NetworkTransform a page after that. Not a big deal though, there is a ToC with links on the right.

Testing builds and using command-line helpers are mentioned in a Tip before they are introduced and explained in the
RPCs section. That should probably get pulled up into the first section with that link to the documentation on it.

### Basic Components Section

> Step 5. Select UnityTransport as the Network Transport.

There's a little more to it than what this says, but it's pretty simple. For consistency, this step could be spelled out a little more like other steps.

> Step 10. Drag the Player prefab from the Project tab into the PlayerPrefab slot you created in the Inspector tab.

I'm just wondering, is there no way to automatically "rebuild" the list by finding all Prefabs that have a NetworkObject component? This is not feedback, I can follow up on this question in forums or discord.

> Step 12. Save the scene by selecting File > Save.

Ctrl-S is easier!

> Tip: Use the command line helper to test the build out before continuing.

This concept is introduced later in the RPCs section, with a link to the documentation. Also, I don't think it instructed the reader to make a build yet.

### RPCs Section

> Server Received the RPC #1

Supplied sample code actually starts at #0

Suggestion: After directing them to add the GUI code to choose server/host/client, and then run multiple instances of the build, it could be a good time to go ahead and mention MPPM. I just tried installing MPPM 0.1.0 at this point in the getting started guide, and it works. But I know, it's 2023+ and experimental.

Host+Client mode has issues in the RpcTest code and spams this:

	Only the owner can invoke a ServerRpc that requires ownership!
	RpcTest:TestServerRpc (int) (at Assets/Scripts/RpcTest.cs:27)
	RpcTest:TestClientRpc (int) (at Assets/Scripts/RpcTest.cs:20)

It happens with standalone builds and with MPPM. I believe it's fixable by adding checks for IsOwner/IsHost.
	

### NetworkTransform Section

It would be slightly more fun to include some basic sample code to check button input for moving the player manually.

**Comment by armstrongl** [comment]
@jeffposey Thanks so much for putting this thoughtful issue together. I'm going through it and making changes now 😄

**Comment by armstrongl** [comment]
@jeffposey I will push up these changes with #933 this week. Thanks again for all your feedback! <3
