### ISSUE TITLE
Feedback for ocs/basics/connection-approval.md

### ISSUE THREAD

**Issue by FancyApricot** [Unity-Technologies/com.unity.multiplayer.docs#935]
The NetworkManager.ConnectionApprovalResponse does not have the property called 'Reason' that the example uses
https://docs-multiplayer.unity3d.com/netcode/current/api/Unity.Netcode.NetworkManager.ConnectionApprovalResponse/index.html

**Comment by armstrongl** [comment]
Hi @FancyApricot ! I'm looking into this. I suspect it might have changed between releases and just wasn't updated. I'll follow up soon 🙂

**Comment by armstrongl** [comment]
@FancyApricot. which version of NGO are you using? The Reason property was added in 1.2; however, there have been some issues 1.2 not showing up in the Editor.
