### ISSUE TITLE
Client reconnection

### ISSUE THREAD

**Issue by PaulYoSwek** [Unity-Technologies/com.unity.multiplayer.docs#936]
There is a small section that explains very quickly on how to handle disconnection,
but I would like to have a more in depth explanation on how to handle disconnection.

**Suggestions**:
Add some code examples to show what should be called where when a player disconnects.
I understand certain systems need to be shutdown, does this happen OnDestroy or?
How can the client re connect again, how can he retrieve the lobby code again?
We need to handle setting up the game for that client our self  I assume, meaning if objects were destroyed / placed when he was connected.

**Comment by armstrongl** [comment]
Hi @PaulYoSwek ! Thanks for the feedback. Have you seen the code examples on the [Session management topic](https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/session-management)?  We also have an article covering [Reconnecting mid-game](https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/reconnecting-mid-game)).

The code example on the session management page doesn't explicitly address retrieving a lobby code after reconnecting, but it does demonstrate how to save and reassociate data with a player when they disconnect and reconnect using the Player Object approach.

There's also some light coverage of this in the UGS Lobby documentation [here](https://docs.unity.com/lobby/en/manual/reconnect-to-lobby).
