### ISSUE TITLE
In scene placed prefabs not calling to OnNetworkSpawn automatically

### ISSUE THREAD

**Issue by DanielJimenezMorales** [Unity-Technologies/com.unity.multiplayer.docs#943]
When I start Client, Server or Host, The In scene placed prefabs from that scene does not instantiate correctly. This means that the Network Behaviour script does not get its NetworkObject component and OnNetworkSpawn is not being called automatically.

I have followed the documentation steps but it is not working
![image](https://user-images.githubusercontent.com/64079694/215296785-3149fbfe-2486-485a-90b7-c88a7f5e3a62.png)

**Steps to reproduce the behavior:**
1. Create an empty gameObject
2. Add a NetworkObject component to it
3. Add a NetworkBehaviour script (You can create one from zero with a debug.log inside its OnNetworkSpawn method)

The expected behaviour is that it should get called the code inside OnNetworkSpawn

![image](https://user-images.githubusercontent.com/64079694/215296458-9f313b5d-852c-4e5e-8ce4-f66750d83cb9.png)
![image](https://user-images.githubusercontent.com/64079694/215296636-7c2de0b7-6cb7-4709-b527-87d08801d65d.png)
![image](https://user-images.githubusercontent.com/64079694/215296735-294e7bb1-c44a-4055-b145-70664b7a9303.png)

UnityEditor
 - OS: Windows
 - Netcode version: 1.2.0
 - Unity Version: 2021.3.2f1 LTS

**Additional info:**

**Comment by DanielJimenezMorales** [comment]
Edit:
I have seen that the In scene placed NetworkObjects get spawned, but the NetworkBehaviour components dont (This means that the OnNetworkSpawn method is not called)

**Comment by DanielJimenezMorales** [comment]
I have found a fix. If you deactivate Enter Play Mode Options everything works fine. :)

**Comment by s-omeilia-unity** [comment]
Added a note in the documentation.
