### ISSUE TITLE
ConnectionApproval link is dead [1.2.0]

### ISSUE THREAD

**Issue by RikuTheFuffs** [Unity-Technologies/com.unity.multiplayer.docs#946]
**Describe the bug:**

This link is dead:
https://docs-multiplayer.unity3d.com/netcode/current/basics/connection-approval

**Steps to reproduce the behavior:**
1. Go to https://docs-multiplayer.unity3d.com/netcode/current/components/networkmanager/index.html#starting-a-server-host-or-client
2. Scroll until you see the notes box in the "Starting a Server, Host, or Client"
3. Click on "Connection approval" (which points [here](https://docs-multiplayer.unity3d.com/netcode/current/basics/connection-approval))
4. See that it brings to a "Page Not Found" page

**Expected behavior:**
The connection approval page opens. 
[This link ](https://docs-multiplayer.unity3d.com/netcode/current/basics/connection-approval/index.html)brings to the intended page, and seems to be different than the one the text in the screenshot points at

**Screenshots**
![image](https://user-images.githubusercontent.com/27730963/215536307-ec618905-98d9-4186-836f-2c45242cc5a5.png)

**Desktop/Tablet/Smartphone (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version: 109.0.5414.120

**Comment by armstrongl** [comment]
Hi @RikuTheFuffs! Thanks for reporting this issue. Unfortunately, I'm unable to reproduce this issue on my end, but we've been getting a lot of reports of broken URLs. We believe there's a wider issue at play, but we haven't pinned it down yet.

**Comment by RikuTheFuffs** [comment]
I've got [a similar report](https://discord.com/channels/449263083769036810/798150732141690900/1072149505467744276) from members of the community, it seems that the URLs somehow get malformed. Different users are seeing different links. Maybe it's a caching issue? (an old version of the page is being displayed)

**Comment by RikuTheFuffs** [comment]
Seems to be fixed now
