### ISSUE TITLE
Feedback for ocs/tutorials/get-started-with-ngo.md

### ISSUE THREAD

**Issue by zaneshaw** [Unity-Technologies/com.unity.multiplayer.docs#953]
The screenshots regarding the `PlayerPrefab` field is incorrect. It highlights the `NetworkPrefabs` list when it should highlight the `PlayerPrefab` field. This contradicts the text instructions which makes it a little confusing.
I can open a PR for this if you'd like :D

**Comment by RikuTheFuffs** [comment]
@zaneshaw thanks for flagging!

> I can open a PR for this if you'd like :D

It'd be lovely <3

**Comment by JakeUskoski** [comment]
+1 to this issue. It just tripped up a co-worker and I while we were trying to do the tutorial for hackweek. We didn't understand why it wasn't working properly.

I noticed that in the 1.0.0 documentation for the hello world project it has a note talking about how the PlayerPrefab will be automatically spawned if the field is populated, but that isn't in the 1.2.0 documentation. Maybe it would be useful to add? My co-worker is touching this stuff for the first time and was completely lost on why it wasn't working (whereas I've done this tutorial series multiple times before and was able to catch it).

**Comment by armstrongl** [comment]
Hi @zaneshaw, you're more than welcome to open a PR for issues like this! 😄 That said, I'm planning to fix this in #957

**Comment by zaneshaw** [comment]
Thanks! I'll keep that in mind :)
