### ISSUE TITLE
NetworkObjectReference and NetworkBehaviourReference are not linked properly (markdown issue)

### ISSUE THREAD

**Issue by RikuTheFuffs** [Unity-Technologies/com.unity.multiplayer.docs#954]
**Describe the bug:**
Give a clear and concise description of the issue. Include any errors you received.

**Steps to reproduce the behavior:**
1. Go to [this page](https://docs-multiplayer.unity3d.com/netcode/current/basics/networkobject/index.html)
2. Look at the "Note" box at the top
3. Notice how NetworkObjectReference and NetworkBehaviourReference are not linked to their respective pages. Instead, a portion of the url is displayed next to them (maybe an error in markdown formatting?)

**Expected behavior:**
Describe what you expected to happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/27730963/216987253-9bb94da2-60b9-4432-a373-077df859b00c.png)

**Desktop/Tablet/Smartphone (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 109.0.5414.120

**Comment by armstrongl** [comment]
Hi @RikuTheFuffs! Thanks for opening an issue for this. I'll roll out a fix with the next PR 🙂.
