### ISSUE TITLE
Feedback for ocs/tutorials/get-started-with-ngo.md - Note section improperly formatted

### ISSUE THREAD

**Issue by JakeUskoski** [Unity-Technologies/com.unity.multiplayer.docs#956]
In https://docs-multiplayer.unity3d.com/netcode/current/tutorials/get-started-ngo/index.html#test-the-rpcs

There's a section under the codeblock styled sample of what the server and client communicating back and forth should look like which has

```
:::note

<The text of the note>

:::
```

Instead of it presenting as a note. I've included a picture of the section as well:
<img width="964" alt="image" src="https://user-images.githubusercontent.com/12035372/217031591-d50dd4d4-7cd6-4d79-a565-25b6e4f3aa2b.png">

**Comment by armstrongl** [comment]
Nice catch! I'm pushing out a fix for this in #957 🙂
