### ISSUE TITLE
Screenshot content doesn't match doc description

### ISSUE THREAD

**Issue by cosformula** [Unity-Technologies/com.unity.multiplayer.docs#963]
**Describe the bug:**
The screenshot instruction doesn't match the doc instruction on [get-started-ngo](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/get-started-ngo/index.html#create-an-object-to-spawn-for-each-connected-player), follow the instructions of the screenshot will not work correctly.

Doc says **Drag the Player Prefab from the Project tab into the PlayerPrefab**, but the provided snapshot shows dragging the player prefab to NetworkPrefabs.

![image](https://user-images.githubusercontent.com/18232501/218061316-17c53200-ed36-4497-8e33-22705107d943.png)
<img width="687" alt="image" src="https://user-images.githubusercontent.com/18232501/218062434-dc5ed3b9-aa91-483d-9749-1b9e17f04a27.png">

**Steps to reproduce the behavior:**
1. Go to [get-started-ngo](https://docs-multiplayer.unity3d.com/netcode/current/tutorials/get-started-ngo/index.html#create-an-object-to-spawn-for-each-connected-player)
2. Follow the instructions

**Expected behavior:**
N/A

**Screenshots**
N/A

**Desktop/Tablet/Smartphone (please complete the following information):**
N/A

**Additional info:**
N/A

**Comment by LPLafontaineB** [comment]
Thank you @cosformula for submitting this bug! The screenshot was indeed incorrect and a fix for this is included in #951 cc. @armstrongl

**Comment by armstrongl** [comment]
Yes, as @LPLafontaineB said, this is in progress. I should be able to merge it today.
