### ISSUE TITLE
Feedback for ocs/tutorials/command-line-helper.md

### ISSUE THREAD

**Issue by juliaorenstein** [Unity-Technologies/com.unity.multiplayer.docs#965]
[Multiplayer Play Mode package](https://docs-multiplayer.unity3d.com/netcode/tools/mppm.md) link is broken at https://docs-multiplayer.unity3d.com/netcode/current/tutorials/command-line-helper/index.html

**Comment by armstrongl** [comment]
Hi @juliaorenstein, this should be fixed now. I just tested it in my browser, and it's working, but let me know if you still hit an issue.
