### ISSUE TITLE
Feedback for ocs/components/networkanimator.md

### ISSUE THREAD

**Issue by gabagpereira** [Unity-Technologies/com.unity.multiplayer.docs#966]
The title of the page is "Introduction", when it should be "NetworkAnimator". This makes it hard to come across this topic through the contents sidebar.

![image](https://user-images.githubusercontent.com/72309552/218493726-eba60d05-7732-4ef2-be33-a2daa48701bb.png)

**Comment by armstrongl** [comment]
Hi @gabagpereira, thanks for calling this out! I'll fix it ASAP
