### ISSUE TITLE
Feedback for ocs/tutorials/command-line-helper.md

### ISSUE THREAD

**Issue by juliaorenstein** [Unity-Technologies/com.unity.multiplayer.docs#976]
The Mac commands at the bottom didn't work for me, and I found two issues:

<Path to Project>/Build/HelloWorld.app/Contents/MacOS/<Project Name> -mode server -logfile - & ; ~ <Path to Project>/Build/HelloWorld.app/Contents/MacOS/<Project Name> -mode client -logfile -

- This issue applies to all three sample command line entries: The "Build" directory doesn't exist, so I had to omit that so the path was <Path to Project>/HelloWorld.app/...
- This issue applies just to the last one, which lets you test the server and the client simultaneously. And, the tilde before for the second argument returned me to my home directory, which is not where I was starting from and so I was getting a permission denied error, and the second argument didn't register. Removing the tilde worked for me!

Also, as somebody who isn't familiar with networking (and C#, and Unity, etc) I was unsure what I was looking for, and didn't know how to tell if the script was "working" beyond seeing the game pop up (which would happen without the script). A sample output would be helpful!

**Comment by armstrongl** [comment]
Thanks for opening this issue @juliaorenstein! I'll fix it (along with a few others) in #992. I might not get the sample output in this PR, though.
