### ISSUE TITLE
Feedback for ocs/advanced-topics/reconnecting-mid-game.md

### ISSUE THREAD

**Issue by MuhammedResulBilkil** [Unity-Technologies/com.unity.multiplayer.docs#988]
This paragraph is duplicated [here](https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/reconnecting-mid-game) 

"When using [scene management](https://docs-multiplayer.unity3d.com/netcode/current/basics/scenemanagement/scene-management-overview) and multiple additive scenes, there is a specific case to keep in mind. During the synchronization process, which launches when connecting to a game, if the client's active main scene is the same as the server's, it won't initiate a scene load in single mode for that scene. Instead, it will load all additive scenes that are currently loaded on the server. This means that if the client has additive scenes currently loaded, it won't unload them like it would if the client's main scene was different than the server's.

For example, if during a game, the server loads main scene A, then additively loads scenes B and C, the client has all three loaded. If the client disconnects and reconnects without changing scenes, the scene synchronization process recognizes that main scene A is already loaded on the client, and then simply proceeds to load the server's additive scenes. In that case, the client loads the scenes B and C a second time and then has two copies of those scenes loaded.
However, if, while the client is disconnected, the server loads or unloads a scene additively, there is also a mismatch between the scenes loaded on the client and on the server. For example, if the server unloads scene C and loads scene D, the client loads scene D when synchronizing, but doesn't unload scene C, so the client has loaded scenes A, B (twice), C, and D, while the server only has loaded scenes A, B, and D.

If you want to avoid this behavior, you can
Load a different scene in single mode on the client when disconnecting
Unload additive scenes on the client when disconnecting
Unload additive scenes on the client when reconnecting
Use the NetworkSceneManager.VerifySceneBeforeLoading callback to prevent loading scenes already loaded on the client. However, this won't handle unloading scenes that were unloaded by the server between the time the client disconnected and reconnected."

**Comment by armstrongl** [comment]
Hi @MuhammedResulBilkil, thanks for reporting this!
