### ISSUE TITLE
Feedback for /docs/tutorials/helloworldintro.md

### ISSUE THREAD

**Issue by JustinMinnaar** [Unity-Technologies/com.unity.multiplayer.docs#99]
I tried creating a new project, using the Package Manager, +, Github as instructed, however, I get the following error:

[Package Manager Window] Error adding package: https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi.git?path=/com.unity.multiplayer.mlapi#0.1.0.
UnityEditor.EditorApplication:Internal_CallUpdateFunctions ()

I may be worthwhile to add this error and its resolution to this page, just in case anyone else hits it. I don't know what the resolution is or what this means.

**Comment by Briancoughlin** [comment]
can you let me know if you copied using the copy button or copy via select all method?

**Comment by Briancoughlin** [comment]
There doesnt appear to be any whitespace in the HTML generated 
`<div class="token-line" style="color:#bfc7d5"><span class="token plain">https://github.com/Unity-Technologies/com.unity.multiplayer.mlapi.git?path=/com.unity.multiplayer.mlapi#0.1.0</span></div>`

Not sure if we should try adding some whitespace stripping CSS to the style.

I propose adding a warning/Guidance admonition as below

_We recommend that you use the 'Copy' function in the code block above to copy the URL as other methods may result in errors._

**Comment by Briancoughlin** [comment]
![image](https://user-images.githubusercontent.com/76997526/112456913-1f306780-8d53-11eb-8f59-818298734af0.png)
 
This is the proposed update

**Comment by lkrell** [comment]
Completed, this change will be live today. We are also updating the CSS to make the copy button brighter, easier to see!
