### ISSUE TITLE
Feedback for ocs/tutorials/testing/testing_locally.md

### ISSUE THREAD

**Issue by powersupersport** [Unity-Technologies/com.unity.multiplayer.docs#991]
https://docs-multiplayer.unity3d.com/netcode/current/tutorials/testing/testing_locally/index.html
*Use the find tool in the browser (Ctrl + F)*

> ParallelSync is not supported by Unity. Please see the **repositor** for more information

Is **repositor** a typo by chance? Repository?

**Comment by armstrongl** [comment]
Yes, this is a typo. Thanks for catching it! 😄
