### ISSUE TITLE
Authorative -> Authoritative

### ISSUE THREAD

**Issue by powersupersport** [Unity-Technologies/com.unity.multiplayer.docs#998]
Authorative and Authoritative words are being used inconsistently throughout the documentation. Autho**rat**ive seems to be the incorrect version. It's autho**ritat**ive.

Examples (Use Ctrl + F in the browser):

https://docs-multiplayer.unity3d.com/netcode/current/learn/listen-server-host-architecture
> Listen servers are also much cheaper then dedicated servers because there is no need to run dedicated authorative servers for your game.

https://docs-multiplayer.unity3d.com/netcode/current/learn/bitesize/bitesize-spaceshooter
> Server Authorative Physics Movement

**Comment by armstrongl** [comment]
Hi @powersupersport, thanks for bringing this to our attention! We have a lot of quality issues throughout the multiplayer documentation that we've been working to resolve. I'll open a PR to fix this.
